/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.CategoriaEmpleadoDao;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.CategoriaEmpleado;

/**
 *
 * @author aleja
 */
public class PanelIngresarCategoriaEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarCategoria
     */
    public PanelIngresarCategoriaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreCategoriaEmpleado = new javax.swing.JLabel();
        inputDescCategoriaEmp = new javax.swing.JTextField();
        btnIngresarCategoria = new javax.swing.JButton();
        btnLimpiarIngresocategoriaEmpleado = new javax.swing.JButton();
        btnVolverIngresoCategoriaEmpleado = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Ingreso Categoria"));

        labelNombreCategoriaEmpleado.setText("Nombre categoria Empleado:");

        inputDescCategoriaEmp.setForeground(new java.awt.Color(153, 153, 153));
        inputDescCategoriaEmp.setText("Ingrese Categoria Empleado");
        inputDescCategoriaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDescCategoriaEmpActionPerformed(evt);
            }
        });

        btnIngresarCategoria.setText("Ingreso Categoria");
        btnIngresarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCategoriaActionPerformed(evt);
            }
        });

        btnLimpiarIngresocategoriaEmpleado.setText("Limpiar");
        btnLimpiarIngresocategoriaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresocategoriaEmpleadoActionPerformed(evt);
            }
        });

        btnVolverIngresoCategoriaEmpleado.setText("Volver");
        btnVolverIngresoCategoriaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverIngresoCategoriaEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresarCategoria)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiarIngresocategoriaEmpleado)
                        .addGap(33, 33, 33)
                        .addComponent(btnVolverIngresoCategoriaEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombreCategoriaEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDescCategoriaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombreCategoriaEmpleado)
                    .addComponent(inputDescCategoriaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarCategoria)
                    .addComponent(btnLimpiarIngresocategoriaEmpleado)
                    .addComponent(btnVolverIngresoCategoriaEmpleado))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputDescCategoriaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDescCategoriaEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDescCategoriaEmpActionPerformed

    private void btnIngresarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCategoriaActionPerformed

        String desc_categoria_emp;

        desc_categoria_emp = inputDescCategoriaEmp.getText();

        CategoriaEmpleado categoriaEmpleado = new CategoriaEmpleado(0, desc_categoria_emp);

        CategoriaEmpleadoDao categoriaEmpleadoDao = new CategoriaEmpleadoDao();

        if(categoriaEmpleadoDao.buscarCategoriaEmpleado(desc_categoria_emp).isEmpty()){

            categoriaEmpleadoDao.IngresarCategoriaEmpleado(categoriaEmpleado);
            JOptionPane.showMessageDialog(this,"Categoria Empleado: "+
                categoriaEmpleado.getDesc_categoria_emp() +
                " Ingresada");

        }else{
            JOptionPane.showMessageDialog(this,"ERROR Categoria Empleado: "+
                categoriaEmpleado.getDesc_categoria_emp() +
                " Ya Existe");
        }
    }//GEN-LAST:event_btnIngresarCategoriaActionPerformed

    private void btnLimpiarIngresocategoriaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresocategoriaEmpleadoActionPerformed
        //Deberia probar con initComponent();
        
        inputDescCategoriaEmp.setText("");
        
//        JTextField input;
//
//        for(int i = 0; i < panelingresarCategoriaEmpleado.getComponentCount(); i++){
//            if(panelingresarCategoriaEmpleado.getComponent(i).getName().equals("javax.swing.JTextField")){
//
//                input = (JTextField)panelingresarCategoriaEmpleado.getComponent(i);
//                input.setText("");
//            }
//        }
    }//GEN-LAST:event_btnLimpiarIngresocategoriaEmpleadoActionPerformed

    private void btnVolverIngresoCategoriaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverIngresoCategoriaEmpleadoActionPerformed
        //dispose();
    }//GEN-LAST:event_btnVolverIngresoCategoriaEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarCategoria;
    private javax.swing.JButton btnLimpiarIngresocategoriaEmpleado;
    private javax.swing.JButton btnVolverIngresoCategoriaEmpleado;
    private javax.swing.JTextField inputDescCategoriaEmp;
    private javax.swing.JLabel labelNombreCategoriaEmpleado;
    // End of variables declaration//GEN-END:variables
}
