/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.CategoriaEmpleadoDao;
import controlador.MisMetodos;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.CategoriaEmpleado;

/**
 *
 * @author aleja
 */
public class PanelIngresarCategoriaEmpleado extends javax.swing.JPanel {
    
    CategoriaEmpleadoDao categoriaEmpleadoDao= new CategoriaEmpleadoDao();
    ArrayList<Component> listadoInputsNoVacios = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorNoVacios = new ArrayList<>();
    
    /**
     * Creates new form PanelIngresarCategoria
     */
    public PanelIngresarCategoriaEmpleado() {
        initComponents();
        MisMetodos.panelCamposErrorInicializador(this);
        //LLenar Listado Inputs no vacios
        listadoInputsNoVacios.add(inputdesc_categoria_emp);
        //LLenar Listado LabelError
        listadoLabelErrorNoVacios.add(labelErrordesc_categoria_emp);        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreCategoriaEmpleado = new javax.swing.JLabel();
        inputdesc_categoria_emp = new javax.swing.JTextField();
        btnIngresarCategoria = new javax.swing.JButton();
        btnLimpiarIngresocategoriaEmpleado = new javax.swing.JButton();
        labelErrordesc_categoria_emp = new javax.swing.JLabel();
        panelTituloPanelIngresoCategoria = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Ingreso Categoria"));

        labelNombreCategoriaEmpleado.setText("Nombre categoría Empleado:");

        inputdesc_categoria_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputdesc_categoria_emp.setText("Ingrese Categoria Empleado");
        inputdesc_categoria_emp.setName("inputdesc_categoria_emp"); // NOI18N
        inputdesc_categoria_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputdesc_categoria_empActionPerformed(evt);
            }
        });

        btnIngresarCategoria.setText("Ingreso Categoria");
        btnIngresarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCategoriaActionPerformed(evt);
            }
        });

        btnLimpiarIngresocategoriaEmpleado.setText("Limpiar");
        btnLimpiarIngresocategoriaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresocategoriaEmpleadoActionPerformed(evt);
            }
        });

        labelErrordesc_categoria_emp.setForeground(new java.awt.Color(255, 0, 51));
        labelErrordesc_categoria_emp.setText("Algun Texto");
        labelErrordesc_categoria_emp.setName("labelErrordesc_categoria_emp"); // NOI18N

        panelTituloPanelIngresoCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        panelTituloPanelIngresoCategoria.setText("Ingreso Nueva Categoría Empleado");
        panelTituloPanelIngresoCategoria.setName("panelTituloPanelIngresoCategoria"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnIngresarCategoria)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiarIngresocategoriaEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelNombreCategoriaEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelErrordesc_categoria_emp)
                            .addComponent(inputdesc_categoria_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTituloPanelIngresoCategoria)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelTituloPanelIngresoCategoria)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombreCategoriaEmpleado)
                    .addComponent(inputdesc_categoria_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrordesc_categoria_emp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarCategoria)
                    .addComponent(btnLimpiarIngresocategoriaEmpleado))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputdesc_categoria_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputdesc_categoria_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputdesc_categoria_empActionPerformed

    private void btnIngresarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCategoriaActionPerformed
        if(MisMetodos.InputExisteVacio(listadoInputsNoVacios)){
            MisMetodos.inputsNoPuedenEstarVacios(listadoLabelErrorNoVacios, listadoInputsNoVacios);
        }else{
            if(!MisMetodos.inputNumeroEntero(inputdesc_categoria_emp)){
                String desc_categoria_emp;
                desc_categoria_emp = inputdesc_categoria_emp.getText();
                CategoriaEmpleado categoriaEmpleado = new CategoriaEmpleado(0, desc_categoria_emp);

                if(categoriaEmpleadoDao.buscarCategoriaEmpleado(desc_categoria_emp).isEmpty()){

                    categoriaEmpleadoDao.IngresarCategoriaEmpleado(categoriaEmpleado);
                    JOptionPane.showMessageDialog(this,"Categoria Empleado: "+
                        categoriaEmpleado.getDesc_categoria_emp() +
                        " Ingresada");
                }else{
                    JOptionPane.showMessageDialog(this,"ERROR Categoria Empleado: "+
                        categoriaEmpleado.getDesc_categoria_emp() +
                        " Ya Existe");
                }
            }else{
                MisMetodos.labelMensajeValidacion(labelErrordesc_categoria_emp,"El campo no puede ser un número","error");
            }           
        }
    }//GEN-LAST:event_btnIngresarCategoriaActionPerformed

    private void btnLimpiarIngresocategoriaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresocategoriaEmpleadoActionPerformed
       MisMetodos.panelLimpiarComponentes(this);
       MisMetodos.panelCamposErrorInicializador(this);
    }//GEN-LAST:event_btnLimpiarIngresocategoriaEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarCategoria;
    private javax.swing.JButton btnLimpiarIngresocategoriaEmpleado;
    private javax.swing.JTextField inputdesc_categoria_emp;
    private javax.swing.JLabel labelErrordesc_categoria_emp;
    private javax.swing.JLabel labelNombreCategoriaEmpleado;
    private javax.swing.JLabel panelTituloPanelIngresoCategoria;
    // End of variables declaration//GEN-END:variables
}
