/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.EstadoCivilDao;
import controlador.MisMetodos;
import controlador.PropietarioDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.EstadoCivil;
import modelo.Propietario;

/**
 *
 * @author aleja
 */
public class PanelIngresarPropietario extends javax.swing.JPanel {
    Propietario propietario;
    PropietarioDao propietarioDao = new PropietarioDao();
    EstadoCivilDao estadoCivilDao = new EstadoCivilDao();
    
    /**
     * Creates new form PanelIngresarPropietarioMisMetord     */
    public PanelIngresarPropietario() {
        initComponents();
        MisMetodos.comboboxLLenado(comboBoxEstadoCivil, estadoCivilDao.todosLosEstadoCivil());
        MisMetodos.panelCamposErrorInicializador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNombre_prop = new javax.swing.JTextField();
        labelNombre_prop = new javax.swing.JLabel();
        inputDireccion_prop = new javax.swing.JTextField();
        labelDireccion_prop = new javax.swing.JLabel();
        inputFonofijo_prop = new javax.swing.JTextField();
        labelId_estcivil = new javax.swing.JLabel();
        inputCelular_prop = new javax.swing.JTextField();
        labelFonofijo_prop = new javax.swing.JLabel();
        inputId_comuna = new javax.swing.JTextField();
        labelCelular_prop = new javax.swing.JLabel();
        btnIngresarNuevoPropietario = new javax.swing.JButton();
        labelId_Comuna = new javax.swing.JLabel();
        btnLimpiarIngresoNuevoPropietario = new javax.swing.JButton();
        inputNumrut_prop = new javax.swing.JTextField();
        labelNumrut_prop = new javax.swing.JLabel();
        inputDvrut_prop = new javax.swing.JTextField();
        comboBoxEstadoCivil = new javax.swing.JComboBox<>();
        labelDvrut_prop = new javax.swing.JLabel();
        inputAppaterno_prop = new javax.swing.JTextField();
        labelAppaterno_prop = new javax.swing.JLabel();
        inputApmaterno_prop = new javax.swing.JTextField();
        labelApmaterno_prop = new javax.swing.JLabel();
        labelErrorNrutPropietarioObligatorio = new javax.swing.JLabel();
        labelErrorRutPropietarioObligatorio = new javax.swing.JLabel();
        labelErrorApellidoPaternoPropietarioObligatorio = new javax.swing.JLabel();
        labelErrorApellidoMaternoPropietarioObligatorio = new javax.swing.JLabel();
        labelErrorNombrePropietarioObligatorio = new javax.swing.JLabel();
        labelErrorDireccionPropietarioObligatorio = new javax.swing.JLabel();
        labelErrorEstadoCivilObligatorio = new javax.swing.JLabel();
        labelErrorFonoFijoPropietarioObligatorio = new javax.swing.JLabel();
        labelErrorCelularPropietario = new javax.swing.JLabel();
        labelErrorComunaObligatorio = new javax.swing.JLabel();
        labelTituloIngresarPropietario = new javax.swing.JLabel();

        inputNombre_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputNombre_prop.setText("Ingrese Nombre Propietario");

        labelNombre_prop.setText("Nombre Propietario");

        inputDireccion_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputDireccion_prop.setText("Ingrese Direccion Propietario");

        labelDireccion_prop.setText("Dirección Propietario");

        inputFonofijo_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputFonofijo_prop.setText("Ingrese Fono Fijo Propietario");

        labelId_estcivil.setText("Id Estado Civil");

        inputCelular_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputCelular_prop.setText("Ingrese Celular Propietario");

        labelFonofijo_prop.setText("Fono fijo Propietario");

        inputId_comuna.setForeground(new java.awt.Color(153, 153, 153));
        inputId_comuna.setText("Ingrese Id Comuna");

        labelCelular_prop.setText("Celular Propietario");

        btnIngresarNuevoPropietario.setText("Ingresar Nuevo Propietario");
        btnIngresarNuevoPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNuevoPropietarioActionPerformed(evt);
            }
        });

        labelId_Comuna.setText("Id Comuna");

        btnLimpiarIngresoNuevoPropietario.setText("Limpiar");
        btnLimpiarIngresoNuevoPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoNuevoPropietarioActionPerformed(evt);
            }
        });

        inputNumrut_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputNumrut_prop.setText("Ingrese Numero Rut Propietario");

        labelNumrut_prop.setText("Nro Rut Propietario");

        inputDvrut_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputDvrut_prop.setText("Ingrese DV Rut Propietario");

        labelDvrut_prop.setText("DV Rut Propietario");

        inputAppaterno_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputAppaterno_prop.setText("Ingrese Apellido Paterno");

        labelAppaterno_prop.setText("Apellido Paterno Propietario");

        inputApmaterno_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputApmaterno_prop.setText("Ingrese Apellido Materno");

        labelApmaterno_prop.setText("Apellido Materno Propietario");

        labelErrorNrutPropietarioObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorNrutPropietarioObligatorio.setText("Nro Rut Propietario Obligatorio");
        labelErrorNrutPropietarioObligatorio.setName("labelErrorNrutPropietarioObligatorio"); // NOI18N

        labelErrorRutPropietarioObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorRutPropietarioObligatorio.setText("DV Rut Propietario Obligatorio");
        labelErrorRutPropietarioObligatorio.setName("labelErrorRutPropietarioObligatorio"); // NOI18N

        labelErrorApellidoPaternoPropietarioObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorApellidoPaternoPropietarioObligatorio.setText("Apellido Paterno Propietario Obligatorio");
        labelErrorApellidoPaternoPropietarioObligatorio.setName("labelErrorApellidoPaternoPropietarioObligatorio"); // NOI18N

        labelErrorApellidoMaternoPropietarioObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorApellidoMaternoPropietarioObligatorio.setText("Apellido Materno Propietario Obligatorio");
        labelErrorApellidoMaternoPropietarioObligatorio.setName("labelErrorApellidoMaternoPropietarioObligatorio"); // NOI18N

        labelErrorNombrePropietarioObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorNombrePropietarioObligatorio.setText("Nombre Propietario Obligatorio");
        labelErrorNombrePropietarioObligatorio.setName("labelErrorNombrePropietarioObligatorio"); // NOI18N

        labelErrorDireccionPropietarioObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorDireccionPropietarioObligatorio.setText("Dirección Propietario Obligatorio");
        labelErrorDireccionPropietarioObligatorio.setName("labelErrorDireccionPropietarioObligatorio"); // NOI18N

        labelErrorEstadoCivilObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorEstadoCivilObligatorio.setText("Estado Civil Obligatorio");
        labelErrorEstadoCivilObligatorio.setName("labelErrorEstadoCivilObligatorio"); // NOI18N

        labelErrorFonoFijoPropietarioObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorFonoFijoPropietarioObligatorio.setText("Fono Fijo Propietario Obligatorio");
        labelErrorFonoFijoPropietarioObligatorio.setName("labelErrorFonoFijoPropietarioObligatorio"); // NOI18N

        labelErrorCelularPropietario.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorCelularPropietario.setText("Celular Propietario Obligatorio");
        labelErrorCelularPropietario.setName("labelErrorCelularPropietario"); // NOI18N

        labelErrorComunaObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorComunaObligatorio.setText("Comuna Obligatorio");
        labelErrorComunaObligatorio.setName("labelErrorComunaObligatorio"); // NOI18N

        labelTituloIngresarPropietario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTituloIngresarPropietario.setText("Ingreso Nuevo Propietario");
        labelTituloIngresarPropietario.setName("labelTituloIngresarPropietario"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNumrut_prop)
                                    .addComponent(labelDvrut_prop)
                                    .addComponent(labelApmaterno_prop)
                                    .addComponent(labelNombre_prop)
                                    .addComponent(labelDireccion_prop)
                                    .addComponent(labelId_estcivil)
                                    .addComponent(labelFonofijo_prop)
                                    .addComponent(labelCelular_prop)
                                    .addComponent(labelId_Comuna)
                                    .addComponent(labelAppaterno_prop))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputDvrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorRutPropietarioObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputCelular_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorCelularPropietario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputId_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorComunaObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputAppaterno_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorApellidoPaternoPropietarioObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputApmaterno_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorApellidoMaternoPropietarioObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputNombre_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorNombrePropietarioObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputDireccion_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorDireccionPropietarioObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputFonofijo_prop, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorFonoFijoPropietarioObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorEstadoCivilObligatorio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputNumrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelErrorNrutPropietarioObligatorio))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnIngresarNuevoPropietario)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarIngresoNuevoPropietario))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(labelTituloIngresarPropietario)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelTituloIngresarPropietario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumrut_prop)
                    .addComponent(inputNumrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorNrutPropietarioObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDvrut_prop)
                    .addComponent(inputDvrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorRutPropietarioObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAppaterno_prop)
                    .addComponent(inputAppaterno_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorApellidoPaternoPropietarioObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApmaterno_prop)
                    .addComponent(inputApmaterno_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorApellidoMaternoPropietarioObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre_prop)
                    .addComponent(inputNombre_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorNombrePropietarioObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccion_prop)
                    .addComponent(inputDireccion_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorDireccionPropietarioObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelId_estcivil)
                        .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelErrorEstadoCivilObligatorio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFonofijo_prop)
                    .addComponent(inputFonofijo_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorFonoFijoPropietarioObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelular_prop)
                    .addComponent(inputCelular_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorCelularPropietario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId_Comuna)
                    .addComponent(inputId_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorComunaObligatorio))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarNuevoPropietario)
                    .addComponent(btnLimpiarIngresoNuevoPropietario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarNuevoPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNuevoPropietarioActionPerformed
        
        int numrut_Prop = Integer.parseInt(String.valueOf(inputNumrut_prop.getText()));

        ArrayList<Propietario> listadopropietario = propietarioDao.buscarPropietario(numrut_Prop);
        ArrayList<EstadoCivil> listadoEstadoCivil = estadoCivilDao.buscarEstadoCivil(String.valueOf(comboBoxEstadoCivil.getSelectedItem()));
        

        if(listadopropietario.isEmpty()){

            char dvrut_prop = String.valueOf(inputDvrut_prop.getText()).charAt(0);
            String appaterno_prop = String.valueOf(inputAppaterno_prop.getText());
            String apmaterno_prop = String.valueOf(inputApmaterno_prop.getText());
            String nombre_prop = String.valueOf(inputNombre_prop.getText());
            String direccion_prop = String.valueOf(inputDireccion_prop.getText());
            
            int id_estcivil = MisMetodos.comboBoxBuscarSeleccion(listadoEstadoCivil);
            //int id_estcivil = buscarSeleccionComboboxEstadoCivil(String.valueOf(comboBoxEstadoCivil.getSelectedItem()));
            
            String fonofijo_prop = String.valueOf(inputFonofijo_prop.getText());
            String celular_prop = String.valueOf(inputCelular_prop.getText());
            int id_comuna = Integer.parseInt(String.valueOf(inputId_comuna.getText()));

            propietario = new Propietario(numrut_Prop, dvrut_prop, appaterno_prop, apmaterno_prop, nombre_prop, direccion_prop, id_estcivil, fonofijo_prop, celular_prop, id_comuna);

            propietarioDao.ingresarPropietario(propietario);

            JOptionPane.showMessageDialog(this,"Propietario Ingresado Correctamente");
        }else{
            JOptionPane.showMessageDialog(this, "Propietario Ya Existe");
        }

    }//GEN-LAST:event_btnIngresarNuevoPropietarioActionPerformed

    private void btnLimpiarIngresoNuevoPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoNuevoPropietarioActionPerformed
        MisMetodos.panelLimpiarComponentes(this);
    }//GEN-LAST:event_btnLimpiarIngresoNuevoPropietarioActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarNuevoPropietario;
    private javax.swing.JButton btnLimpiarIngresoNuevoPropietario;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil;
    private javax.swing.JTextField inputApmaterno_prop;
    private javax.swing.JTextField inputAppaterno_prop;
    private javax.swing.JTextField inputCelular_prop;
    private javax.swing.JTextField inputDireccion_prop;
    private javax.swing.JTextField inputDvrut_prop;
    private javax.swing.JTextField inputFonofijo_prop;
    private javax.swing.JTextField inputId_comuna;
    private javax.swing.JTextField inputNombre_prop;
    private javax.swing.JTextField inputNumrut_prop;
    private javax.swing.JLabel labelApmaterno_prop;
    private javax.swing.JLabel labelAppaterno_prop;
    private javax.swing.JLabel labelCelular_prop;
    private javax.swing.JLabel labelDireccion_prop;
    private javax.swing.JLabel labelDvrut_prop;
    private javax.swing.JLabel labelErrorApellidoMaternoPropietarioObligatorio;
    private javax.swing.JLabel labelErrorApellidoPaternoPropietarioObligatorio;
    private javax.swing.JLabel labelErrorCelularPropietario;
    private javax.swing.JLabel labelErrorComunaObligatorio;
    private javax.swing.JLabel labelErrorDireccionPropietarioObligatorio;
    private javax.swing.JLabel labelErrorEstadoCivilObligatorio;
    private javax.swing.JLabel labelErrorFonoFijoPropietarioObligatorio;
    private javax.swing.JLabel labelErrorNombrePropietarioObligatorio;
    private javax.swing.JLabel labelErrorNrutPropietarioObligatorio;
    private javax.swing.JLabel labelErrorRutPropietarioObligatorio;
    private javax.swing.JLabel labelFonofijo_prop;
    private javax.swing.JLabel labelId_Comuna;
    private javax.swing.JLabel labelId_estcivil;
    private javax.swing.JLabel labelNombre_prop;
    private javax.swing.JLabel labelNumrut_prop;
    private javax.swing.JLabel labelTituloIngresarPropietario;
    // End of variables declaration//GEN-END:variables
}
