/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import modelo.Empleado;
import controlador.EmpleadoDao;
import controlador.MisMetodos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */
public class PanelMostrarEmpleado extends javax.swing.JPanel {
    Empleado empleado;
    EmpleadoDao empleadoDao = new EmpleadoDao();
    MisMetodos misMetodos = new MisMetodos();
    DefaultTableModel tabla;
        
    /**
     * Creates new form PanelMostrarEmpleado
     */
    public PanelMostrarEmpleado() {
        initComponents();
        btnMostrarTodosLosEmpleados.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarEmpleado = new javax.swing.JButton();
        btnIngresarNuevoEmpleado = new javax.swing.JButton();
        labelTitulopanelMostrarEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTodosLosEmpleados = new javax.swing.JTable();
        btnBuscarEmpleado = new javax.swing.JButton();
        btnMostrarTodosLosEmpleados = new javax.swing.JButton();
        btnEditarEmpleado = new javax.swing.JButton();

        btnEliminarEmpleado.setText("Eliminar Empleado");
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        btnIngresarNuevoEmpleado.setText("Ingresar Nuevo Empleado");
        btnIngresarNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNuevoEmpleadoActionPerformed(evt);
            }
        });

        labelTitulopanelMostrarEmpleado.setText("Empleados");

        tablaTodosLosEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Dv", "Apellido Paterno", "Apellido Materno", "Nombre", "Direccion", "Estado Civil", "Fono Fijo", "Celular", "Fecha Nacimiento", "Fecha Ingreso", "Sueldo", "Comuna", "Categoria Empleado", "Rut Supervisor"
            }
        ));
        jScrollPane1.setViewportView(tablaTodosLosEmpleados);
        if (tablaTodosLosEmpleados.getColumnModel().getColumnCount() > 0) {
            tablaTodosLosEmpleados.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(1).setPreferredWidth(10);
            tablaTodosLosEmpleados.getColumnModel().getColumn(5).setPreferredWidth(200);
            tablaTodosLosEmpleados.getColumnModel().getColumn(6).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(7).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(8).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(9).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(10).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(11).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(12).setPreferredWidth(50);
            tablaTodosLosEmpleados.getColumnModel().getColumn(13).setResizable(false);
            tablaTodosLosEmpleados.getColumnModel().getColumn(13).setPreferredWidth(75);
            tablaTodosLosEmpleados.getColumnModel().getColumn(14).setResizable(false);
            tablaTodosLosEmpleados.getColumnModel().getColumn(14).setPreferredWidth(50);
        }

        btnBuscarEmpleado.setText("Buscar Empleado");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        btnMostrarTodosLosEmpleados.setText("Mostrar Todos los Empleados");
        btnMostrarTodosLosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosLosEmpleadosActionPerformed(evt);
            }
        });

        btnEditarEmpleado.setText("Editar Empleado");
        btnEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(757, 757, 757)
                        .addComponent(labelTitulopanelMostrarEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(btnIngresarNuevoEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarTodosLosEmpleados)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarEmpleado)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulopanelMostrarEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarNuevoEmpleado)
                    .addComponent(btnBuscarEmpleado)
                    .addComponent(btnMostrarTodosLosEmpleados)
                    .addComponent(btnEditarEmpleado)
                    .addComponent(btnEliminarEmpleado))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        int filaSeleccionada = tablaTodosLosEmpleados.getSelectedRow();

        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar Una Fila");
        }else{

            int numrut_emp = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 0)));
            char dvrut_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 1)).charAt(0);
            String appaterno_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 2));
            String apmaterno_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada,3));
            String nombre_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 4));
            String direccion_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 5));
            int id_estcivil = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 6)));
            String fonofijo_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 7));
            String celular_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 8));
            String fecnac_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 9)); //debe ser formato yyyy-mm-d = d
            String fecing_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 10));
            int sueldo_emp = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 11)));
            int id_comuna = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 12)));
            int id_categoria_emp = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 13)));
            int numrut_supervisor = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 14)));

            empleado = new Empleado(numrut_emp, dvrut_emp, appaterno_emp, apmaterno_emp, nombre_emp, direccion_emp, id_estcivil, fonofijo_emp, celular_emp, fecnac_emp, fecing_emp, sueldo_emp, id_comuna, id_categoria_emp, numrut_supervisor);
            empleadoDao.eliminarEmpleado(empleado);

            JOptionPane.showMessageDialog(this, "Empleado Eliminado");

            btnMostrarTodosLosEmpleados.doClick();
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnIngresarNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNuevoEmpleadoActionPerformed
        VentanaIngresarEmpleado ventanaIngresarEmpleado = new VentanaIngresarEmpleado();
        misMetodos.abrirVentana(ventanaIngresarEmpleado,"Ingreso Nuevo Empleado");
    }//GEN-LAST:event_btnIngresarNuevoEmpleadoActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed

        tabla= (DefaultTableModel)tablaTodosLosEmpleados.getModel();
        
        int inputnumrut_emp = Integer.parseInt(JOptionPane.showInputDialog("Ingrese Rut Empleado A Buscar"));
        ArrayList<Empleado> listaempleados = empleadoDao.buscarEmpleado(inputnumrut_emp);

        misMetodos.tablaLimpiar(tablaTodosLosEmpleados);

        if(listaempleados.isEmpty()){
            JOptionPane.showMessageDialog(this,"Empleado No Existe");
        }else{
            String [][] datoslistadoEmpleados = new String[listaempleados.size()][15];

            for (int i = 0; i < listaempleados.size(); i++) {
                datoslistadoEmpleados [i][0] = String.valueOf(listaempleados.get(i).getNumrut_emp());
                datoslistadoEmpleados [i][1] = String.valueOf(listaempleados.get(i).getDvrut_emp());
                datoslistadoEmpleados [i][2] = String.valueOf(listaempleados.get(i).getAppaterno_emp());
                datoslistadoEmpleados [i][3] = String.valueOf(listaempleados.get(i).getApmaterno_emp());
                datoslistadoEmpleados [i][4] = String.valueOf(listaempleados.get(i).getNombre_emp());
                datoslistadoEmpleados [i][5] = String.valueOf(listaempleados.get(i).getDireccion_emp());
                datoslistadoEmpleados [i][6] = String.valueOf(listaempleados.get(i).getId_estcivil());
                datoslistadoEmpleados [i][7] = String.valueOf(listaempleados.get(i).getFonofijo_emp());
                datoslistadoEmpleados [i][8] = String.valueOf(listaempleados.get(i).getCelular_emp());
                datoslistadoEmpleados [i][9] = String.valueOf(listaempleados.get(i).getFecnac_emp());
                datoslistadoEmpleados [i][10] = String.valueOf(listaempleados.get(i).getFecing_emp());
                datoslistadoEmpleados [i][11] = String.valueOf(listaempleados.get(i).getSueldo_emp());
                datoslistadoEmpleados [i][12] = String.valueOf(listaempleados.get(i).getId_comuna());
                datoslistadoEmpleados [i][13] = String.valueOf(listaempleados.get(i).getId_categoria_emp());
                datoslistadoEmpleados [i][14] = String.valueOf(listaempleados.get(i).getNumrut_supervisor());

                tabla.addRow(datoslistadoEmpleados[i]);
            }
            tablaTodosLosEmpleados.setModel(tabla);
            misMetodos.tablaCentrarDatos(tablaTodosLosEmpleados);
        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnMostrarTodosLosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosLosEmpleadosActionPerformed
        tabla = (DefaultTableModel)tablaTodosLosEmpleados.getModel();
        ArrayList<Empleado> listaempleados = empleadoDao.todosLosEmpleados();

        misMetodos.tablaLimpiar(tablaTodosLosEmpleados);

        if(listaempleados.isEmpty()){
            JOptionPane.showMessageDialog(this, "No Existen Empleados");
        }else{
            String [][] datoslistadoEmpleados = new String[listaempleados.size()][15];

            for (int i = 0; i < listaempleados.size(); i++) {
                datoslistadoEmpleados [i][0] = String.valueOf(listaempleados.get(i).getNumrut_emp());
                datoslistadoEmpleados [i][1] = String.valueOf(listaempleados.get(i).getDvrut_emp());
                datoslistadoEmpleados [i][2] = String.valueOf(listaempleados.get(i).getAppaterno_emp());
                datoslistadoEmpleados [i][3] = String.valueOf(listaempleados.get(i).getApmaterno_emp());
                datoslistadoEmpleados [i][4] = String.valueOf(listaempleados.get(i).getNombre_emp());
                datoslistadoEmpleados [i][5] = String.valueOf(listaempleados.get(i).getDireccion_emp());
                datoslistadoEmpleados [i][6] = String.valueOf(listaempleados.get(i).getId_estcivil());
                datoslistadoEmpleados [i][7] = String.valueOf(listaempleados.get(i).getFonofijo_emp());
                datoslistadoEmpleados [i][8] = String.valueOf(listaempleados.get(i).getCelular_emp());
                datoslistadoEmpleados [i][9] = String.valueOf(listaempleados.get(i).getFecnac_emp());
                datoslistadoEmpleados [i][10] = String.valueOf(listaempleados.get(i).getFecing_emp());
                datoslistadoEmpleados [i][11] = String.valueOf(listaempleados.get(i).getSueldo_emp());
                datoslistadoEmpleados [i][12] = String.valueOf(listaempleados.get(i).getId_comuna());
                datoslistadoEmpleados [i][13] = String.valueOf(listaempleados.get(i).getId_categoria_emp());
                datoslistadoEmpleados [i][14] = String.valueOf(listaempleados.get(i).getNumrut_supervisor());

                tabla.addRow(datoslistadoEmpleados[i]);
            }
        }
        tablaTodosLosEmpleados.setModel(tabla);
        misMetodos.tablaCentrarDatos(tablaTodosLosEmpleados);
    }//GEN-LAST:event_btnMostrarTodosLosEmpleadosActionPerformed

    private void btnEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoActionPerformed

        int filaSeleccionada = tablaTodosLosEmpleados.getSelectedRow();

        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar Una Fila");
        }else{

            int numrut_emp = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 0)));
            char dvrut_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 1)).charAt(0);
            String appaterno_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 2));
            String apmaterno_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada,3));
            String nombre_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 4));
            String direccion_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 5));
            int id_estcivil = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 6)));
            String fonofijo_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 7));
            String celular_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 8));
            String fecnac_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 9)); //debe ser formato yyyy-mm-d = d
            String fecing_emp = String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 10));
            int sueldo_emp = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 11)));
            int id_comuna = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 12)));
            int id_categoria_emp = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 13)));
            int numrut_supervisor = Integer.parseInt(String.valueOf(tablaTodosLosEmpleados.getValueAt(filaSeleccionada, 14)));

            empleado = new Empleado(numrut_emp, dvrut_emp, appaterno_emp, apmaterno_emp, nombre_emp, direccion_emp, id_estcivil, fonofijo_emp, celular_emp, fecnac_emp, fecing_emp, sueldo_emp, id_comuna, id_categoria_emp, numrut_supervisor);
            empleadoDao.actualizarEmpleado(empleado);

            JOptionPane.showMessageDialog(this, "Empleado Actualizado");
        }
    }//GEN-LAST:event_btnEditarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnEditarEmpleado;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnIngresarNuevoEmpleado;
    private javax.swing.JButton btnMostrarTodosLosEmpleados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulopanelMostrarEmpleado;
    private javax.swing.JTable tablaTodosLosEmpleados;
    // End of variables declaration//GEN-END:variables
}
