/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.CategoriaEmpleadoDao;
import controlador.ComunaDao;
import controlador.EmpleadoDao;
import controlador.EstadoCivilDao;
import controlador.MisMetodos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.CategoriaEmpleado;
import modelo.Comuna;
import modelo.Empleado;
import modelo.EstadoCivil;

/**
 *
 * @author aleja
 */
public class PanelIngresarEmpleado extends javax.swing.JPanel {
    MisMetodos misMetodos = new MisMetodos();
    Empleado empleado;
    
    EmpleadoDao empleadoDao = new EmpleadoDao();
    EstadoCivilDao estadocivilDao = new EstadoCivilDao();
    CategoriaEmpleadoDao categoriaEmpleadoDao = new CategoriaEmpleadoDao();
    ComunaDao comunaDao = new ComunaDao();
    /**
     * Creates new form PanelIngresarEmpleado
     */
    public PanelIngresarEmpleado() {
        initComponents();
        misMetodos.comboboxLLenado(comboBoxCategoriaEmpleado, categoriaEmpleadoDao.todasLasCategoriaEmpleado());
        misMetodos.comboboxLLenado(comboBoxComunaEmpleado, comunaDao.mostrarComunas());
        misMetodos.comboboxLLenado(comboBoxEstadoCivil, estadocivilDao.todosLosEstadoCivil());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputCelular_emp = new javax.swing.JTextField();
        inputFecnac_emp = new javax.swing.JTextField();
        labelDVRutEmpleado = new javax.swing.JLabel();
        inputFecing_emp = new javax.swing.JTextField();
        labelApellidoPaternoEmpleado = new javax.swing.JLabel();
        inputSueldo_emp = new javax.swing.JTextField();
        labelApellidoMaternoEmpleado = new javax.swing.JLabel();
        inputNumrut_supervisor = new javax.swing.JTextField();
        labelNombreEmpleado = new javax.swing.JLabel();
        inputFonofijo_emp = new javax.swing.JTextField();
        labelDireccionEmpleado = new javax.swing.JLabel();
        labelIdEstadoCivil = new javax.swing.JLabel();
        labelCelularEmpleado = new javax.swing.JLabel();
        labelFechaNacimientoEmpleado = new javax.swing.JLabel();
        comboBoxEstadoCivil = new javax.swing.JComboBox<>();
        labelFechaIngresoEmpleado = new javax.swing.JLabel();
        labelSueldoEmpleado = new javax.swing.JLabel();
        labelIdComunaEmpleado = new javax.swing.JLabel();
        labelIdCategoriaEmpleado = new javax.swing.JLabel();
        labelRutSupervisor = new javax.swing.JLabel();
        inputNumRut_emp = new javax.swing.JTextField();
        labelFonoFijoEmpleado = new javax.swing.JLabel();
        inputDvRut_emp = new javax.swing.JTextField();
        inputAppaterno_emp = new javax.swing.JTextField();
        inputApmaterno_emp = new javax.swing.JTextField();
        inputNombre_emp = new javax.swing.JTextField();
        inputDireccion_emp = new javax.swing.JTextField();
        comboBoxComunaEmpleado = new javax.swing.JComboBox<>();
        comboBoxCategoriaEmpleado = new javax.swing.JComboBox<>();
        labelRutEmpleado = new javax.swing.JLabel();
        btnIngresarNuevoEmpleado = new javax.swing.JButton();
        btnLimpiarNuevoEmpleado = new javax.swing.JButton();

        inputCelular_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputCelular_emp.setText("Ingrese Celular Empleado");

        inputFecnac_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputFecnac_emp.setText("Ingrese Fecha Nacimiento Empleado");

        labelDVRutEmpleado.setText("DV Rut Empleado");

        inputFecing_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputFecing_emp.setText("Ingrese Fecha Ingreso Empleado");

        labelApellidoPaternoEmpleado.setText("Apellido Paterno empleado");

        inputSueldo_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputSueldo_emp.setText("Ingrese Sueldo Empleado");

        labelApellidoMaternoEmpleado.setText("Apellido Materno Empleado");

        inputNumrut_supervisor.setForeground(new java.awt.Color(153, 153, 153));
        inputNumrut_supervisor.setText("Ingrese Rut Supervisor Empleado");

        labelNombreEmpleado.setText("Nombre Empleado");

        inputFonofijo_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputFonofijo_emp.setText("Ingrese Telefono Fijo Empleado");

        labelDireccionEmpleado.setText("Dirección Empleado");

        labelIdEstadoCivil.setText("Estado Civil");

        labelCelularEmpleado.setText("Celular Empleado");

        labelFechaNacimientoEmpleado.setText("Fecha Nacimiento Empleado");

        comboBoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEstadoCivilActionPerformed(evt);
            }
        });

        labelFechaIngresoEmpleado.setText("Fecha Ingreso Empleado");

        labelSueldoEmpleado.setText("Sueldo Empleado");

        labelIdComunaEmpleado.setText("Id Comuna Empleado");

        labelIdCategoriaEmpleado.setText("Id Categoria Empleado");

        labelRutSupervisor.setText("rut Supervisor");

        inputNumRut_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputNumRut_emp.setText("Ingrese Rut Empleado");
        inputNumRut_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumRut_empActionPerformed(evt);
            }
        });

        labelFonoFijoEmpleado.setText("Fono fijo Empleado");

        inputDvRut_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputDvRut_emp.setText("Ingrese DV Rut Empleado");
        inputDvRut_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDvRut_empActionPerformed(evt);
            }
        });

        inputAppaterno_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputAppaterno_emp.setText("Ingrese Apellido Paterno Empleado");
        inputAppaterno_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAppaterno_empActionPerformed(evt);
            }
        });

        inputApmaterno_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputApmaterno_emp.setText("Ingrese Apellido Materno Empleado");

        inputNombre_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputNombre_emp.setText("Ingrese Nombre Empleado");

        inputDireccion_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputDireccion_emp.setText("Ingrese Direccion Empleado");

        labelRutEmpleado.setText("Rut Empleado");

        btnIngresarNuevoEmpleado.setText("Ingresar Nuevo Empleado");
        btnIngresarNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNuevoEmpleadoActionPerformed(evt);
            }
        });

        btnLimpiarNuevoEmpleado.setText("Limpiar");
        btnLimpiarNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarNuevoEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRutEmpleado)
                    .addComponent(labelDVRutEmpleado)
                    .addComponent(labelApellidoPaternoEmpleado)
                    .addComponent(labelApellidoMaternoEmpleado)
                    .addComponent(labelNombreEmpleado)
                    .addComponent(labelDireccionEmpleado)
                    .addComponent(labelIdEstadoCivil)
                    .addComponent(labelFonoFijoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelularEmpleado)
                    .addComponent(labelFechaNacimientoEmpleado)
                    .addComponent(labelFechaIngresoEmpleado)
                    .addComponent(labelSueldoEmpleado)
                    .addComponent(labelIdCategoriaEmpleado)
                    .addComponent(labelRutSupervisor)
                    .addComponent(labelIdComunaEmpleado))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxComunaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNumRut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDvRut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAppaterno_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputApmaterno_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNombre_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDireccion_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFonofijo_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCelular_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFecing_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFecnac_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSueldo_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNumrut_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxCategoriaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnIngresarNuevoEmpleado)
                .addGap(49, 49, 49)
                .addComponent(btnLimpiarNuevoEmpleado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRutEmpleado)
                    .addComponent(inputNumRut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDVRutEmpleado)
                    .addComponent(inputDvRut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoPaternoEmpleado)
                    .addComponent(inputAppaterno_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoMaternoEmpleado)
                    .addComponent(inputApmaterno_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreEmpleado)
                    .addComponent(inputNombre_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccionEmpleado)
                    .addComponent(inputDireccion_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdEstadoCivil)
                    .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFonoFijoEmpleado)
                    .addComponent(inputFonofijo_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelularEmpleado)
                    .addComponent(inputCelular_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaNacimientoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFecnac_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaIngresoEmpleado)
                    .addComponent(inputFecing_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSueldoEmpleado)
                    .addComponent(inputSueldo_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdComunaEmpleado)
                    .addComponent(comboBoxComunaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdCategoriaEmpleado)
                    .addComponent(comboBoxCategoriaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRutSupervisor)
                    .addComponent(inputNumrut_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarNuevoEmpleado)
                    .addComponent(btnLimpiarNuevoEmpleado))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputNumRut_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumRut_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumRut_empActionPerformed

    private void inputDvRut_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDvRut_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDvRut_empActionPerformed

    private void inputAppaterno_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAppaterno_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAppaterno_empActionPerformed

    private void btnIngresarNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNuevoEmpleadoActionPerformed
        
        ArrayList<Comuna> resultadoComuna = comunaDao.buscarComuna((String)comboBoxComunaEmpleado.getSelectedItem());
        ArrayList<EstadoCivil> resultadoEstadoCivil = estadocivilDao.buscarEstadoCivil((String)comboBoxEstadoCivil.getSelectedItem());
        ArrayList<CategoriaEmpleado> resultadoCategoriaEmpleado = categoriaEmpleadoDao.buscarCategoriaEmpleado((String)comboBoxCategoriaEmpleado.getSelectedItem());
        
        String dvrut = inputDvRut_emp.getText();

        int numrut_emp = Integer.parseInt(inputNumRut_emp.getText());
        char dvrut_emp = dvrut.charAt(0);
        String appaterno_emp = inputAppaterno_emp.getText();
        String apmaterno_emp = inputApmaterno_emp.getText();
        String nombre_emp = inputNombre_emp.getText();
        String direccion_emp = inputDireccion_emp.getText();
        
        int id_estcivil = misMetodos.comboBoxBuscarSeleccion(resultadoEstadoCivil);
        //int id_estcivil = seleccionComboBoxEstadoCivil((String)comboBoxEstadoCivil.getSelectedItem());
        
        String fonofijo_emp = inputFonofijo_emp.getText();
        String celular_emp = inputCelular_emp.getText();
        String fecnac_emp = inputFecnac_emp.getText(); //debe ser formato yyyy-mm-d = ind
        String fecing_emp = inputFecing_emp.getText();
        int sueldo_emp = Integer.parseInt(inputSueldo_emp.getText());
        
        int id_comuna = misMetodos.comboBoxBuscarSeleccion(resultadoComuna);;
        
        int id_categoria_emp = misMetodos.comboBoxBuscarSeleccion(resultadoCategoriaEmpleado);
        
        int numrut_supervisor = Integer.parseInt(inputNumrut_supervisor.getText());

        ArrayList<Empleado> listaEmpleado = empleadoDao.buscarEmpleado(numrut_emp);

        if(listaEmpleado.isEmpty()){
            empleado = new Empleado(numrut_emp, dvrut_emp, appaterno_emp, apmaterno_emp, nombre_emp, direccion_emp, id_estcivil, fonofijo_emp, celular_emp, fecnac_emp, fecing_emp, sueldo_emp, id_comuna, id_categoria_emp, numrut_supervisor);

            empleadoDao.ingresarEmpleado(empleado);

            JOptionPane.showMessageDialog(this,"Empleado Ingresado");
        }else{
            JOptionPane.showMessageDialog(this, "Empleado Ya Existe");
        }
    }//GEN-LAST:event_btnIngresarNuevoEmpleadoActionPerformed

    private void btnLimpiarNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarNuevoEmpleadoActionPerformed
        misMetodos.panelLimpiarComponentes(this);
    }//GEN-LAST:event_btnLimpiarNuevoEmpleadoActionPerformed

    private void comboBoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEstadoCivilActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarNuevoEmpleado;
    private javax.swing.JButton btnLimpiarNuevoEmpleado;
    private javax.swing.JComboBox<String> comboBoxCategoriaEmpleado;
    private javax.swing.JComboBox<String> comboBoxComunaEmpleado;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil;
    private javax.swing.JTextField inputApmaterno_emp;
    private javax.swing.JTextField inputAppaterno_emp;
    private javax.swing.JTextField inputCelular_emp;
    private javax.swing.JTextField inputDireccion_emp;
    private javax.swing.JTextField inputDvRut_emp;
    private javax.swing.JTextField inputFecing_emp;
    private javax.swing.JTextField inputFecnac_emp;
    private javax.swing.JTextField inputFonofijo_emp;
    private javax.swing.JTextField inputNombre_emp;
    private javax.swing.JTextField inputNumRut_emp;
    private javax.swing.JTextField inputNumrut_supervisor;
    private javax.swing.JTextField inputSueldo_emp;
    private javax.swing.JLabel labelApellidoMaternoEmpleado;
    private javax.swing.JLabel labelApellidoPaternoEmpleado;
    private javax.swing.JLabel labelCelularEmpleado;
    private javax.swing.JLabel labelDVRutEmpleado;
    private javax.swing.JLabel labelDireccionEmpleado;
    private javax.swing.JLabel labelFechaIngresoEmpleado;
    private javax.swing.JLabel labelFechaNacimientoEmpleado;
    private javax.swing.JLabel labelFonoFijoEmpleado;
    private javax.swing.JLabel labelIdCategoriaEmpleado;
    private javax.swing.JLabel labelIdComunaEmpleado;
    private javax.swing.JLabel labelIdEstadoCivil;
    private javax.swing.JLabel labelNombreEmpleado;
    private javax.swing.JLabel labelRutEmpleado;
    private javax.swing.JLabel labelRutSupervisor;
    private javax.swing.JLabel labelSueldoEmpleado;
    // End of variables declaration//GEN-END:variables
}
