/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import controlador.MisMetodos;
import modelo.TipoPropiedad;
import controlador.TipoPropiedadDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author aleja
 */
public class PanelIngresarTipoPropiedad extends javax.swing.JPanel {
    MisMetodos misMetodos = new MisMetodos();
    TipoPropiedad tipoPropiedad;
    /**
     * Creates new form PanelIngresarTipoPropiedad
     */
    public PanelIngresarTipoPropiedad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputDesc_tipo_propiedad = new javax.swing.JTextField();
        btnIngresoTipoPropiedad = new javax.swing.JButton();
        btnLimpiarIngresoTipoPropiedad = new javax.swing.JButton();
        labelId_tipo_propiedad = new javax.swing.JLabel();
        labelDesc_tipo_propiedad = new javax.swing.JLabel();
        inputId_tipo_propiedad = new javax.swing.JTextField();

        inputDesc_tipo_propiedad.setForeground(new java.awt.Color(153, 153, 153));
        inputDesc_tipo_propiedad.setText("Ingrese Descripcion Tipo Propiedad");

        btnIngresoTipoPropiedad.setText("Ingreso Tipo Propiedad");
        btnIngresoTipoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoTipoPropiedadActionPerformed(evt);
            }
        });

        btnLimpiarIngresoTipoPropiedad.setText("Limpiar");
        btnLimpiarIngresoTipoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoTipoPropiedadActionPerformed(evt);
            }
        });

        labelId_tipo_propiedad.setText("Id Tipo Propiedad");

        labelDesc_tipo_propiedad.setText("Descripción Tipo Propiedad");

        inputId_tipo_propiedad.setForeground(new java.awt.Color(153, 153, 153));
        inputId_tipo_propiedad.setText("Ingrese Id Tipo Propiedad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelId_tipo_propiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDesc_tipo_propiedad, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDesc_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputId_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnIngresoTipoPropiedad)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarIngresoTipoPropiedad)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId_tipo_propiedad)
                    .addComponent(inputId_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesc_tipo_propiedad)
                    .addComponent(inputDesc_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresoTipoPropiedad)
                    .addComponent(btnLimpiarIngresoTipoPropiedad))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoTipoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoTipoPropiedadActionPerformed

        TipoPropiedadDao tipoPropiedadDao = new TipoPropiedadDao();

        char id_tipoPropiedad  = inputId_tipo_propiedad.getText().charAt(0);
        String desc_tipoPropiedad = inputDesc_tipo_propiedad.getText();

        ArrayList <TipoPropiedad> listadoTipoPropiedadID = tipoPropiedadDao.buscarTipoPropiedadPorId(id_tipoPropiedad);
        ArrayList <TipoPropiedad> listadoTipoPropiedadDescripcion = tipoPropiedadDao.buscarTipoPropiedadPorDescripcion(desc_tipoPropiedad);

        if(listadoTipoPropiedadID.isEmpty()){

            TipoPropiedad tipoPropiedad = new TipoPropiedad(id_tipoPropiedad, desc_tipoPropiedad);

            tipoPropiedadDao.ingresarTipoPropiedad(tipoPropiedad);

            JOptionPane.showMessageDialog(this,"Tipo Propiedad Ingresada");
        }
        else{
            JOptionPane.showMessageDialog(this,"Tipo propiedad Ya existe o La Descripcion Ya existe");
        }

    }//GEN-LAST:event_btnIngresoTipoPropiedadActionPerformed

    private void btnLimpiarIngresoTipoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoTipoPropiedadActionPerformed
        misMetodos.panelLimpiarComponentes(this);
    }//GEN-LAST:event_btnLimpiarIngresoTipoPropiedadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoTipoPropiedad;
    private javax.swing.JButton btnLimpiarIngresoTipoPropiedad;
    private javax.swing.JTextField inputDesc_tipo_propiedad;
    private javax.swing.JTextField inputId_tipo_propiedad;
    private javax.swing.JLabel labelDesc_tipo_propiedad;
    private javax.swing.JLabel labelId_tipo_propiedad;
    // End of variables declaration//GEN-END:variables
}
