/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import modelo.PropiedadArrendada;
import modelo.Propiedad;
import modelo.Cliente;
import controlador.PropiedadArrendadaDao;
import controlador.ClienteDao;
import controlador.MisMetodos;
import controlador.PropiedadDao;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author aleja
 */
public class PanelIngresarPropiedadArrendada extends javax.swing.JPanel {
    
    ClienteDao clienteDao = new ClienteDao();
    PropiedadDao propiedadDao = new PropiedadDao();
    PropiedadArrendada propiedadArrendada;
    
    PropiedadArrendadaDao propiedadArrendadaDao = new PropiedadArrendadaDao();
    
    ArrayList<Component> listadoInputsNoVacios = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorNoVacios = new ArrayList<>();
    ArrayList<Component> listadoInputsNumeros = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorNumeros = new ArrayList<>();
    ArrayList<Component> listadoInputfechas = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorfechas = new ArrayList<>();
    
    
    /**
     * Creates new form PanelIngresarPropiedadArrendada
     */
    public PanelIngresarPropiedadArrendada() {
        initComponents();
        MisMetodos.panelCamposErrorInicializador(this);
        
        listadoInputsNoVacios.add(inputnro_propiedad);
        listadoInputsNoVacios.add(inputfecini_arriendo);
        listadoInputsNoVacios.add(inputnumrut_cli);
        
        listadoLabelErrorNoVacios.add(labelErrornro_propiedad);
        listadoLabelErrorNoVacios.add(labelErrorfecini_arriendo);
        listadoLabelErrorNoVacios.add(labelErrornumrut_cli);
        
        listadoInputsNumeros.add(inputnro_propiedad);
        listadoInputsNumeros.add(inputnumrut_cli);
        
        listadoLabelErrorNumeros.add(labelErrornro_propiedad);
        listadoLabelErrorNumeros.add(labelErrornumrut_cli);
        
        listadoInputfechas.add(inputfecini_arriendo);
        listadoInputfechas.add(inputfecter_arriendo);
        
        listadoLabelErrorfechas.add(labelErrorfecini_arriendo);
        listadoLabelErrorfechas.add(labelErrorfecter_arriendo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresoArriendoPropiedad = new javax.swing.JButton();
        btnLimpiarIngresoArriendoPropiedad = new javax.swing.JButton();
        labelNro_propiedad = new javax.swing.JLabel();
        btnIngresarPropiedad = new javax.swing.JButton();
        labelFecini_arriendo = new javax.swing.JLabel();
        btnIngresarCliente = new javax.swing.JButton();
        labelFecter_arriendo = new javax.swing.JLabel();
        labelNumrut_cli = new javax.swing.JLabel();
        inputnro_propiedad = new javax.swing.JTextField();
        inputfecini_arriendo = new javax.swing.JTextField();
        inputfecter_arriendo = new javax.swing.JTextField();
        inputnumrut_cli = new javax.swing.JTextField();
        labelErrornro_propiedad = new javax.swing.JLabel();
        labelErrorfecini_arriendo = new javax.swing.JLabel();
        labelErrorfecter_arriendo = new javax.swing.JLabel();
        labelErrornumrut_cli = new javax.swing.JLabel();
        labelTituloPanelIngresarPropiedadArrendada = new javax.swing.JLabel();

        btnIngresoArriendoPropiedad.setText("Ingreso Arriendo Propiedad");
        btnIngresoArriendoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoArriendoPropiedadActionPerformed(evt);
            }
        });

        btnLimpiarIngresoArriendoPropiedad.setText("Limpiar");
        btnLimpiarIngresoArriendoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoArriendoPropiedadActionPerformed(evt);
            }
        });

        labelNro_propiedad.setText("Nro Propiedad");

        btnIngresarPropiedad.setText("Ingresar Nueva Propiedad");
        btnIngresarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPropiedadActionPerformed(evt);
            }
        });

        labelFecini_arriendo.setText("Fecha Inicio Arriendo");

        btnIngresarCliente.setText("Ingresar Nuevo Cliente");
        btnIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarClienteActionPerformed(evt);
            }
        });

        labelFecter_arriendo.setText("Fecha Término Arriendo");

        labelNumrut_cli.setText("Nro Rut Cliente");

        inputnro_propiedad.setForeground(new java.awt.Color(153, 153, 153));
        inputnro_propiedad.setText("Ingrese Numero Propiedad");
        inputnro_propiedad.setName("inputnro_propiedad"); // NOI18N

        inputfecini_arriendo.setForeground(new java.awt.Color(153, 153, 153));
        inputfecini_arriendo.setText("Ingrese Fecha Inicio Arriendo");
        inputfecini_arriendo.setName("inputfecini_arriendo"); // NOI18N
        inputfecini_arriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputfecini_arriendoActionPerformed(evt);
            }
        });

        inputfecter_arriendo.setForeground(new java.awt.Color(153, 153, 153));
        inputfecter_arriendo.setText("Ingrese Fecha Termino Arriendo");
        inputfecter_arriendo.setName("inputfecter_arriendo"); // NOI18N

        inputnumrut_cli.setForeground(new java.awt.Color(153, 153, 153));
        inputnumrut_cli.setText("Ingrese Numero de rut del Cliente");
        inputnumrut_cli.setName("inputnumrut_cli"); // NOI18N

        labelErrornro_propiedad.setForeground(new java.awt.Color(255, 0, 0));
        labelErrornro_propiedad.setText("Algun Texto");
        labelErrornro_propiedad.setName("labelErrornro_propiedad"); // NOI18N

        labelErrorfecini_arriendo.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorfecini_arriendo.setText("Algun texto");
        labelErrorfecini_arriendo.setName("labelErrorfecini_arriendo"); // NOI18N

        labelErrorfecter_arriendo.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorfecter_arriendo.setText("Algun Texto");
        labelErrorfecter_arriendo.setName("labelErrorfecter_arriendo"); // NOI18N

        labelErrornumrut_cli.setForeground(new java.awt.Color(255, 0, 0));
        labelErrornumrut_cli.setText("Algun Texto");
        labelErrornumrut_cli.setName("labelErrornumrut_cli"); // NOI18N

        labelTituloPanelIngresarPropiedadArrendada.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTituloPanelIngresarPropiedadArrendada.setText("Ingreso Nueva Propiedad Arrendada");
        labelTituloPanelIngresarPropiedadArrendada.setName("labelTituloPanelIngresarPropiedadArrendada"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelNumrut_cli)
                                        .addGap(95, 95, 95))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNro_propiedad)
                                            .addComponent(labelFecini_arriendo)
                                            .addComponent(labelFecter_arriendo))
                                        .addGap(49, 49, 49)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelErrornro_propiedad)
                                                    .addComponent(labelErrorfecini_arriendo)
                                                    .addComponent(inputnro_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(74, 74, 74))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputfecini_arriendo)
                                                .addGap(49, 49, 49)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnIngresarPropiedad)
                                            .addComponent(btnIngresarCliente)))
                                    .addComponent(labelErrorfecter_arriendo)
                                    .addComponent(labelErrornumrut_cli)
                                    .addComponent(inputfecter_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputnumrut_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresoArriendoPropiedad)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarIngresoArriendoPropiedad))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(labelTituloPanelIngresarPropiedadArrendada)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelTituloPanelIngresarPropiedadArrendada)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNro_propiedad)
                    .addComponent(inputnro_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarPropiedad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrornro_propiedad)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecini_arriendo)
                    .addComponent(inputfecini_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorfecini_arriendo)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecter_arriendo)
                    .addComponent(inputfecter_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorfecter_arriendo)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumrut_cli)
                    .addComponent(inputnumrut_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(labelErrornumrut_cli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresoArriendoPropiedad)
                    .addComponent(btnLimpiarIngresoArriendoPropiedad))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoArriendoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoArriendoPropiedadActionPerformed
        //Controlar si cliente rut y  numero propiedad son numeros valido                
        MisMetodos.panelCamposErrorInicializador(this);

        boolean existeInputVacio = MisMetodos.InputExisteVacio(listadoInputsNoVacios);
        boolean existeNumeroNoValido = MisMetodos.inputListadoNumeroNoValido(listadoInputsNumeros);
        boolean existeFechaNoValida = MisMetodos.fechaExisteNoValido(listadoInputfechas);
        
        
        boolean nroPropiedadEsNumero =  MisMetodos.inputNumeroEntero(inputnro_propiedad);
        boolean rutClienteEsNumero =  MisMetodos.inputNumeroEntero(inputnumrut_cli);
        boolean fecinicioEsValida = MisMetodos.esFechaValida(inputfecini_arriendo.getText());
        boolean fecterminoEsValida = MisMetodos.esFechaValida(inputfecter_arriendo.getText());
        
        
        
        if(existeInputVacio || existeNumeroNoValido || existeFechaNoValida){
            
            MisMetodos.inputsNoPuedenEstarVacios(listadoLabelErrorNoVacios, listadoInputsNoVacios);
            
            if(!nroPropiedadEsNumero){
                MisMetodos.labelMensajeValidacion(labelErrornro_propiedad, "Ingrese un numero","error");
            }else{
                MisMetodos.labelMensajeValidacion(labelErrornro_propiedad,"Ok", "Ok");                                
            }
            
            if(!rutClienteEsNumero){
                MisMetodos.labelMensajeValidacion(labelErrornumrut_cli, "Ingrese un numero","error");
            }else{
                MisMetodos.labelMensajeValidacion(labelErrornumrut_cli,"Ok", "Ok");
            }
            
            if(!fecinicioEsValida){
                MisMetodos.labelMensajeValidacion(labelErrorfecini_arriendo,"No es una fecha valida","error");
            }else{
                MisMetodos.labelMensajeValidacion(labelErrorfecini_arriendo,"Ok","Ok");
            }
            
            if(!fecterminoEsValida){
                MisMetodos.labelMensajeValidacion(labelErrorfecter_arriendo,"No es una fecha valida","error");
            }else{
                MisMetodos.labelMensajeValidacion(labelErrorfecter_arriendo,"Ok","Ok");
            }
                      
        }else{
            
            MisMetodos.panelCamposErrorInicializador(this);

            boolean clienteExiste = true;
            boolean propiedadExiste = true;
            
            if(clienteDao.buscarCliente(Integer.parseInt(inputnumrut_cli.getText())).isEmpty()){
                MisMetodos.labelMensajeValidacion(labelErrornumrut_cli,"Cliente No Existe", "error");
                clienteExiste = false;
            }
            
            
            if(propiedadDao.buscarPropiedad(Integer.parseInt(inputnro_propiedad.getText())).isEmpty()){
                MisMetodos.labelMensajeValidacion(labelErrornro_propiedad,"Propiedad No Existe", "error");
                propiedadExiste = false;
            }
            
            //INGRESO DE PROPIEDAD
            if(clienteExiste && propiedadExiste){
            
                int nroPropiedad = Integer.parseInt(String.valueOf(inputnro_propiedad.getText()));
                int numrut_cli = Integer.parseInt(String.valueOf(inputnumrut_cli.getText()));

                String fec_inicio = String.valueOf(inputfecini_arriendo.getText());
                String fec_termino = String.valueOf(inputfecter_arriendo.getText());

                propiedadArrendada= new PropiedadArrendada(nroPropiedad, fec_inicio, fec_termino, numrut_cli);
                propiedadArrendadaDao.agregarPropiedadArrendada(propiedadArrendada);

                JOptionPane.showMessageDialog(this,"Arriendo De Propiedad Ingresado Correctamente");
            
            }
        }

    }//GEN-LAST:event_btnIngresoArriendoPropiedadActionPerformed

    private void btnIngresarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPropiedadActionPerformed
        VentanaIngresarPropiedad ventanaIngresarPropiedad = new VentanaIngresarPropiedad();
        MisMetodos.abrirVentana(ventanaIngresarPropiedad,"Ingreso Nueva Propiedad");
    }//GEN-LAST:event_btnIngresarPropiedadActionPerformed

    private void btnIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarClienteActionPerformed
        VentanaIngresarCliente  ventanaIngresarCliente = new VentanaIngresarCliente();
        MisMetodos.abrirVentana(ventanaIngresarCliente, "Registro Cliente");
    }//GEN-LAST:event_btnIngresarClienteActionPerformed

    private void inputfecini_arriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputfecini_arriendoActionPerformed

    }//GEN-LAST:event_inputfecini_arriendoActionPerformed

    private void btnLimpiarIngresoArriendoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoArriendoPropiedadActionPerformed
        MisMetodos.panelLimpiarComponentes(this);
        MisMetodos.panelCamposErrorInicializador(this);

    }//GEN-LAST:event_btnLimpiarIngresoArriendoPropiedadActionPerformed
    
    
    public boolean buscadorPropiedadExiste(int nroPropiedad){
        boolean resultado = true;
        ArrayList<Propiedad> listadoPropiedades = propiedadDao.buscarPropiedad(nroPropiedad);
        
        if(listadoPropiedades.isEmpty()){
            resultado = false;
        }
        
        return resultado;
    }
    
    public boolean buscadorClienteExiste(int numrut_cli){
        boolean resultado = true;        
        ArrayList<Cliente> listadoclientes = clienteDao.buscarCliente(numrut_cli);
        
        if(listadoclientes.isEmpty()){
            resultado = false;
        }
        
        return resultado;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarCliente;
    private javax.swing.JButton btnIngresarPropiedad;
    private javax.swing.JButton btnIngresoArriendoPropiedad;
    private javax.swing.JButton btnLimpiarIngresoArriendoPropiedad;
    private javax.swing.JTextField inputfecini_arriendo;
    private javax.swing.JTextField inputfecter_arriendo;
    private javax.swing.JTextField inputnro_propiedad;
    private javax.swing.JTextField inputnumrut_cli;
    private javax.swing.JLabel labelErrorfecini_arriendo;
    private javax.swing.JLabel labelErrorfecter_arriendo;
    private javax.swing.JLabel labelErrornro_propiedad;
    private javax.swing.JLabel labelErrornumrut_cli;
    private javax.swing.JLabel labelFecini_arriendo;
    private javax.swing.JLabel labelFecter_arriendo;
    private javax.swing.JLabel labelNro_propiedad;
    private javax.swing.JLabel labelNumrut_cli;
    private javax.swing.JLabel labelTituloPanelIngresarPropiedadArrendada;
    // End of variables declaration//GEN-END:variables
}
