/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.EstadoCivilDao;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.EstadoCivil;

/**
 *
 * @author aleja
 */
public class PanelIngresarEstadoCivil extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarEstadoCivil
     */
    public PanelIngresarEstadoCivil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDescripcionEstadoCivil = new javax.swing.JLabel();
        InputDesc_estcivil = new javax.swing.JTextField();
        btnGuardarEstadoCivil = new javax.swing.JButton();
        btnLimpiarEstadoCivil = new javax.swing.JButton();
        btnVolverEstadoCivil = new javax.swing.JButton();

        labelDescripcionEstadoCivil.setText("Nombre Estado Civil: ");

        InputDesc_estcivil.setForeground(new java.awt.Color(153, 153, 153));
        InputDesc_estcivil.setText("Ingrese Estado Civil");

        btnGuardarEstadoCivil.setText("Guardar Estado Civil");
        btnGuardarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstadoCivilActionPerformed(evt);
            }
        });

        btnLimpiarEstadoCivil.setText("Limpiar");
        btnLimpiarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEstadoCivilActionPerformed(evt);
            }
        });

        btnVolverEstadoCivil.setText("Volver");
        btnVolverEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverEstadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescripcionEstadoCivil)
                    .addComponent(btnGuardarEstadoCivil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiarEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolverEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InputDesc_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescripcionEstadoCivil)
                    .addComponent(InputDesc_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEstadoCivil)
                    .addComponent(btnLimpiarEstadoCivil)
                    .addComponent(btnVolverEstadoCivil))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstadoCivilActionPerformed

        String desc_EstCivil;

        desc_EstCivil = InputDesc_estcivil.getText();

        EstadoCivil estadoCivil = new EstadoCivil(0, desc_EstCivil);

        EstadoCivilDao estadoCivilDao = new EstadoCivilDao();

        if(estadoCivilDao.buscarEstadoCivil(desc_EstCivil).isEmpty()){
            estadoCivilDao.agregarEstadoCivil(estadoCivil);

            JOptionPane.showMessageDialog(this, "Estado Civil Ingresado");

        }else{
            JOptionPane.showMessageDialog(this,"Estado Civil Ya Existe");
        }
    }//GEN-LAST:event_btnGuardarEstadoCivilActionPerformed

    private void btnLimpiarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEstadoCivilActionPerformed
        JTextField caja;
        PanelIngresarEstadoCivil panelIngresasrEstadoCivil = new PanelIngresarEstadoCivil();
        for (int i = 0; i < panelIngresasrEstadoCivil.getComponentCount(); i++) {
            if(panelIngresasrEstadoCivil.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)panelIngresasrEstadoCivil.getComponent(i);
                caja.setText("");
            }
        }
    }//GEN-LAST:event_btnLimpiarEstadoCivilActionPerformed

    private void btnVolverEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverEstadoCivilActionPerformed
        //dispose();
    }//GEN-LAST:event_btnVolverEstadoCivilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputDesc_estcivil;
    private javax.swing.JButton btnGuardarEstadoCivil;
    private javax.swing.JButton btnLimpiarEstadoCivil;
    private javax.swing.JButton btnVolverEstadoCivil;
    private javax.swing.JLabel labelDescripcionEstadoCivil;
    // End of variables declaration//GEN-END:variables
}
