/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.EstadoCivilDao;
import controlador.MisMetodos;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.EstadoCivil;

/**
 *
 * @author aleja
 */
public class PanelIngresarEstadoCivil extends javax.swing.JPanel {
    
    ArrayList<Component> listadoInputsNoVacios = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorNoVacios = new ArrayList<>();
    /**
     * Creates new form PanelIngresarEstadoCivil
     */
    
    public PanelIngresarEstadoCivil() {
        initComponents();
        MisMetodos.panelCamposErrorInicializador(this);
        
        listadoInputsNoVacios.add(Inputdesc_Estcivil);
        listadoLabelErrorNoVacios.add(labelErrordesc_Estcivil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDescripcionEstadoCivil = new javax.swing.JLabel();
        Inputdesc_Estcivil = new javax.swing.JTextField();
        btnGuardarEstadoCivil = new javax.swing.JButton();
        btnLimpiarEstadoCivil = new javax.swing.JButton();
        btnVolverEstadoCivil = new javax.swing.JButton();
        labelErrordesc_Estcivil = new javax.swing.JLabel();
        labelTituloPanelIngresarEstadoCivil = new javax.swing.JLabel();

        labelDescripcionEstadoCivil.setText("Nombre Estado Civil: ");

        Inputdesc_Estcivil.setForeground(new java.awt.Color(153, 153, 153));
        Inputdesc_Estcivil.setText("Ingrese Estado Civil");
        Inputdesc_Estcivil.setName("Inputdesc_Estcivil"); // NOI18N

        btnGuardarEstadoCivil.setText("Guardar Estado Civil");
        btnGuardarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstadoCivilActionPerformed(evt);
            }
        });

        btnLimpiarEstadoCivil.setText("Limpiar");
        btnLimpiarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEstadoCivilActionPerformed(evt);
            }
        });

        btnVolverEstadoCivil.setText("Volver");
        btnVolverEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverEstadoCivilActionPerformed(evt);
            }
        });

        labelErrordesc_Estcivil.setForeground(new java.awt.Color(255, 0, 0));
        labelErrordesc_Estcivil.setText("Algun Texto");
        labelErrordesc_Estcivil.setName("labelErrordesc_Estcivil"); // NOI18N

        labelTituloPanelIngresarEstadoCivil.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTituloPanelIngresarEstadoCivil.setText("Ingreso Nuevo Estado Civil");
        labelTituloPanelIngresarEstadoCivil.setName("labelTituloPanelIngresarEstadoCivil"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescripcionEstadoCivil)
                            .addComponent(btnGuardarEstadoCivil))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelErrordesc_Estcivil)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiarEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVolverEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Inputdesc_Estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(labelTituloPanelIngresarEstadoCivil)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTituloPanelIngresarEstadoCivil)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescripcionEstadoCivil)
                    .addComponent(Inputdesc_Estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrordesc_Estcivil)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEstadoCivil)
                    .addComponent(btnLimpiarEstadoCivil)
                    .addComponent(btnVolverEstadoCivil))
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstadoCivilActionPerformed
        if(MisMetodos.InputExisteVacio(listadoInputsNoVacios)){
            MisMetodos.inputsNoPuedenEstarVacios(listadoLabelErrorNoVacios, listadoInputsNoVacios);
            
        }else{
            String desc_EstCivil;

            desc_EstCivil = Inputdesc_Estcivil.getText();

            EstadoCivil estadoCivil = new EstadoCivil(0, desc_EstCivil);

            EstadoCivilDao estadoCivilDao = new EstadoCivilDao();

            if(estadoCivilDao.buscarEstadoCivil(desc_EstCivil).isEmpty()){
                estadoCivilDao.agregarEstadoCivil(estadoCivil);

                JOptionPane.showMessageDialog(this, "Estado Civil Ingresado");

            }else{
                JOptionPane.showMessageDialog(this,"Estado Civil Ya Existe");
            }
        }
    }//GEN-LAST:event_btnGuardarEstadoCivilActionPerformed

    private void btnLimpiarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEstadoCivilActionPerformed
        MisMetodos.panelLimpiarComponentes(this);
        MisMetodos.panelCamposErrorInicializador(this);
    }//GEN-LAST:event_btnLimpiarEstadoCivilActionPerformed

    private void btnVolverEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverEstadoCivilActionPerformed
        //dispose();
    }//GEN-LAST:event_btnVolverEstadoCivilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Inputdesc_Estcivil;
    private javax.swing.JButton btnGuardarEstadoCivil;
    private javax.swing.JButton btnLimpiarEstadoCivil;
    private javax.swing.JButton btnVolverEstadoCivil;
    private javax.swing.JLabel labelDescripcionEstadoCivil;
    private javax.swing.JLabel labelErrordesc_Estcivil;
    private javax.swing.JLabel labelTituloPanelIngresarEstadoCivil;
    // End of variables declaration//GEN-END:variables
}
