/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ComunaDao;
import controlador.EmpleadoDao;
import controlador.MisMetodos;
import controlador.PropiedadDao;
import controlador.PropietarioDao;
import controlador.TipoPropiedadDao;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Comuna;
import modelo.Propiedad;
import modelo.TipoPropiedad;

/**
 *
 * @author aleja
 */
public class PanelIngresarPropiedad extends javax.swing.JPanel {
    
    ComunaDao comunaDao = new ComunaDao();
    PropietarioDao propietarioDao = new PropietarioDao();
    EmpleadoDao empleadoDao = new EmpleadoDao();
    TipoPropiedadDao tipoPropiedadDao = new TipoPropiedadDao();
    ArrayList<Component> listadoInputsNoVacios = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorsNoVacios = new ArrayList<>();
    
    ArrayList<Component> listadoInputsNumeros = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorNumeros = new ArrayList<>();
    
    
    /**
     * Creates new form PanelIngresarPropiedad
     */
    public PanelIngresarPropiedad() {
        initComponents();
        
        MisMetodos.comboboxLLenado(comboBoxid_comuna, comunaDao.mostrarComunas());
        MisMetodos.comboboxLLenado(comboBoxid_tipo_propiedad, tipoPropiedadDao.todosLosTipoPropiedad());
        MisMetodos.panelCamposErrorInicializador(this);
        
        listadoInputsNoVacios.add(inputdireccion_propiedad);
        listadoInputsNoVacios.add(inputsuperficie);
        listadoInputsNoVacios.add(inputvalor_arriendo);
        listadoInputsNoVacios.add(inputnumrut_prop);
        
        listadoLabelErrorsNoVacios.add(labelErrordireccion_propiedad);
        listadoLabelErrorsNoVacios.add(labelErrorsuperficie);
        listadoLabelErrorsNoVacios.add(labelErrorvalor_arriendo);
        listadoLabelErrorsNoVacios.add(labelErrornumrut_prop);
        
        listadoInputsNumeros.add(inputnro_dormitorios);
        listadoInputsNumeros.add(inputnro_banos);
        listadoInputsNumeros.add(inputnumrut_prop);
        listadoInputsNumeros.add(inputnumrut_emp);
        
        listadoLabelErrorNumeros.add(labelErrornro_dormitorios);
        listadoLabelErrorNumeros.add(labelErrornro_banos);
        listadoLabelErrorNumeros.add(labelErrornumrut_prop);
        listadoLabelErrorNumeros.add(labelErrornumrut_emp);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiarIngresoNuevaPropiedad = new javax.swing.JButton();
        labelNumrut_emp = new javax.swing.JLabel();
        inputdireccion_propiedad = new javax.swing.JTextField();
        comboBoxid_tipo_propiedad = new javax.swing.JComboBox<>();
        labelDireccion_propiedad = new javax.swing.JLabel();
        inputsuperficie = new javax.swing.JTextField();
        comboBoxid_comuna = new javax.swing.JComboBox<>();
        labelSuperficie = new javax.swing.JLabel();
        inputnro_dormitorios = new javax.swing.JTextField();
        labelnro_dormitorios = new javax.swing.JLabel();
        inputnro_banos = new javax.swing.JTextField();
        labelNro_banos = new javax.swing.JLabel();
        inputvalor_arriendo = new javax.swing.JTextField();
        labelValor_arriendo = new javax.swing.JLabel();
        inputvalor_gasto_comun = new javax.swing.JTextField();
        labelValor_gasto_comun = new javax.swing.JLabel();
        inputnumrut_prop = new javax.swing.JTextField();
        labelid_tipo_propiedad = new javax.swing.JLabel();
        inputnumrut_emp = new javax.swing.JTextField();
        labelId_comuna = new javax.swing.JLabel();
        btnIngresoNuevaPropiedad = new javax.swing.JButton();
        labelNumrut_prop = new javax.swing.JLabel();
        labelErrordireccion_propiedad = new javax.swing.JLabel();
        labelErrorsuperficie = new javax.swing.JLabel();
        labelErrornro_dormitorios = new javax.swing.JLabel();
        labelErrornro_banos = new javax.swing.JLabel();
        labelErrorvalor_arriendo = new javax.swing.JLabel();
        labelErrorvalor_gasto_comun = new javax.swing.JLabel();
        labelErrorid_tipo_propiedad = new javax.swing.JLabel();
        labelErrorid_comuna = new javax.swing.JLabel();
        labelErrornumrut_prop = new javax.swing.JLabel();
        labelErrornumrut_emp = new javax.swing.JLabel();
        labelTituloPanelIngresarPropiedad = new javax.swing.JLabel();

        btnLimpiarIngresoNuevaPropiedad.setText("Limpiar");
        btnLimpiarIngresoNuevaPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoNuevaPropiedadActionPerformed(evt);
            }
        });

        labelNumrut_emp.setText("Numero Rut Empleado");

        inputdireccion_propiedad.setForeground(new java.awt.Color(153, 153, 153));
        inputdireccion_propiedad.setText("Ingrese Direccion Propiedad");
        inputdireccion_propiedad.setName("inputdireccion_propiedad"); // NOI18N

        comboBoxid_tipo_propiedad.setName("comboBoxid_tipo_propiedad"); // NOI18N

        labelDireccion_propiedad.setText("Dirección Propiedad");

        inputsuperficie.setForeground(new java.awt.Color(153, 153, 153));
        inputsuperficie.setText("Ingrese Superficie Propiedad");
        inputsuperficie.setName("inputsuperficie"); // NOI18N

        comboBoxid_comuna.setName("comboBoxid_comuna"); // NOI18N

        labelSuperficie.setText("Superficie");

        inputnro_dormitorios.setForeground(new java.awt.Color(153, 153, 153));
        inputnro_dormitorios.setText("Ingrese numero de Dormitorios");
        inputnro_dormitorios.setName("inputnro_dormitorios"); // NOI18N

        labelnro_dormitorios.setText("Nro Dormitorios");

        inputnro_banos.setForeground(new java.awt.Color(153, 153, 153));
        inputnro_banos.setText("Ingrese Cantidad de Baños");
        inputnro_banos.setName("inputnro_banos"); // NOI18N

        labelNro_banos.setText("Nro baños");

        inputvalor_arriendo.setForeground(new java.awt.Color(153, 153, 153));
        inputvalor_arriendo.setText("Ingrese valor Arriendo");
        inputvalor_arriendo.setName("inputvalor_arriendo"); // NOI18N

        labelValor_arriendo.setText("Valor Arriendo");

        inputvalor_gasto_comun.setForeground(new java.awt.Color(153, 153, 153));
        inputvalor_gasto_comun.setText("Ingrese Valor Gastos Comunes");
        inputvalor_gasto_comun.setName("inputvalor_gasto_comun"); // NOI18N

        labelValor_gasto_comun.setText("Valor Gasto Común");

        inputnumrut_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputnumrut_prop.setText("Ingrese numero de rut propietario");
        inputnumrut_prop.setName("inputnumrut_prop"); // NOI18N

        labelid_tipo_propiedad.setText("Id tipo propiedad");

        inputnumrut_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputnumrut_emp.setText("Ingrese Rut Empleado");
        inputnumrut_emp.setName("inputnumrut_emp"); // NOI18N

        labelId_comuna.setText("Id Comuna");

        btnIngresoNuevaPropiedad.setText("Ingreso Nueva Propiedad");
        btnIngresoNuevaPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoNuevaPropiedadActionPerformed(evt);
            }
        });

        labelNumrut_prop.setText("Numero Rut Propietario");

        labelErrordireccion_propiedad.setForeground(new java.awt.Color(255, 0, 0));
        labelErrordireccion_propiedad.setText("Algun Texto");
        labelErrordireccion_propiedad.setName("labelErrordireccion_propiedad"); // NOI18N

        labelErrorsuperficie.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorsuperficie.setText("Algun Texto");
        labelErrorsuperficie.setName("labelErrorsuperficie"); // NOI18N

        labelErrornro_dormitorios.setForeground(new java.awt.Color(255, 0, 0));
        labelErrornro_dormitorios.setText("Algun Texto");
        labelErrornro_dormitorios.setName("labelErrornro_dormitorios"); // NOI18N

        labelErrornro_banos.setForeground(new java.awt.Color(255, 0, 0));
        labelErrornro_banos.setText("Algun Texto");
        labelErrornro_banos.setName("labelErrornro_banos"); // NOI18N

        labelErrorvalor_arriendo.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorvalor_arriendo.setText("Algun Texto");
        labelErrorvalor_arriendo.setName("labelErrorvalor_arriendo"); // NOI18N

        labelErrorvalor_gasto_comun.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorvalor_gasto_comun.setText("Algun Texto");
        labelErrorvalor_gasto_comun.setName("labelErrorvalor_gasto_comun"); // NOI18N

        labelErrorid_tipo_propiedad.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorid_tipo_propiedad.setText("Algun Texto");
        labelErrorid_tipo_propiedad.setName("labelErrorid_tipo_propiedad"); // NOI18N

        labelErrorid_comuna.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorid_comuna.setText("Algun Texto");
        labelErrorid_comuna.setName("labelErrorid_comuna"); // NOI18N

        labelErrornumrut_prop.setForeground(new java.awt.Color(255, 0, 0));
        labelErrornumrut_prop.setText("Algun Texto");
        labelErrornumrut_prop.setName("labelErrornumrut_prop"); // NOI18N

        labelErrornumrut_emp.setForeground(new java.awt.Color(255, 0, 0));
        labelErrornumrut_emp.setText("Algun Texto");
        labelErrornumrut_emp.setName("labelErrornumrut_emp"); // NOI18N

        labelTituloPanelIngresarPropiedad.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTituloPanelIngresarPropiedad.setText("Ingreso Nueva Propiedad");
        labelTituloPanelIngresarPropiedad.setName("labelTituloPanelIngresarPropiedad"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelnro_dormitorios)
                            .addComponent(labelValor_arriendo)
                            .addComponent(labelValor_gasto_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelid_tipo_propiedad)
                            .addComponent(labelNumrut_emp)
                            .addComponent(labelNumrut_prop)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDireccion_propiedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelSuperficie))
                            .addComponent(labelNro_banos)
                            .addComponent(labelId_comuna))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputnumrut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelErrornumrut_emp))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(comboBoxid_comuna, 0, 90, Short.MAX_VALUE)
                                            .addComponent(comboBoxid_tipo_propiedad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelErrorid_tipo_propiedad)
                                            .addComponent(labelErrorid_comuna)))
                                    .addComponent(inputnumrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelErrornumrut_prop))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputdireccion_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelErrordireccion_propiedad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputsuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelErrorsuperficie))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputnro_banos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelErrornro_banos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputvalor_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelErrorvalor_arriendo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputvalor_gasto_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelErrorvalor_gasto_comun))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputnro_dormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelErrornro_dormitorios))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnIngresoNuevaPropiedad)
                        .addGap(27, 27, 27)
                        .addComponent(btnLimpiarIngresoNuevaPropiedad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(labelTituloPanelIngresarPropiedad)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelTituloPanelIngresarPropiedad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputdireccion_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDireccion_propiedad)
                            .addComponent(labelErrordireccion_propiedad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputsuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelErrorsuperficie)))
                    .addComponent(labelSuperficie, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputnro_dormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnro_dormitorios)
                    .addComponent(labelErrornro_dormitorios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputnro_banos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNro_banos)
                    .addComponent(labelErrornro_banos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputvalor_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor_arriendo)
                    .addComponent(labelErrorvalor_arriendo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputvalor_gasto_comun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor_gasto_comun)
                    .addComponent(labelErrorvalor_gasto_comun))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxid_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelid_tipo_propiedad)
                    .addComponent(labelErrorid_tipo_propiedad))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxid_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId_comuna)
                    .addComponent(labelErrorid_comuna))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputnumrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumrut_prop)
                    .addComponent(labelErrornumrut_prop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputnumrut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumrut_emp)
                    .addComponent(labelErrornumrut_emp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresoNuevaPropiedad)
                    .addComponent(btnLimpiarIngresoNuevaPropiedad))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarIngresoNuevaPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoNuevaPropiedadActionPerformed
        MisMetodos.panelLimpiarComponentes(this);
        MisMetodos.panelCamposErrorInicializador(this);
    }//GEN-LAST:event_btnLimpiarIngresoNuevaPropiedadActionPerformed

    private void btnIngresoNuevaPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoNuevaPropiedadActionPerformed
        //Aqui aparecen mas condiciones de validacion debido a que se debe verificar la existencia de dueñopropiedad
        //Y tambien el empleado, asu vez controlar el ingreso de valor numerico
        //La superficie debe ser un numero flotante
        
        boolean propietarioExiste;
        boolean empleadoExiste;
        
        boolean rutEmpleadoEsNum = MisMetodos.inputNumeroEntero(inputnumrut_emp);
        boolean rutPropietarioEsNum = MisMetodos.inputNumeroEntero(inputnumrut_prop);
        boolean superficieEsFloat = MisMetodos.inputNumeroFlotante(inputsuperficie);
        
        if(!rutEmpleadoEsNum || !rutPropietarioEsNum || !superficieEsFloat){
            if(rutEmpleadoEsNum){
                empleadoExiste = MisMetodos.existeBusqueda(empleadoDao.buscarEmpleado(Integer.parseInt(inputnumrut_emp.getText())));                
                if(!empleadoExiste){
                    MisMetodos.labelMensajeValidacion(labelErrornumrut_emp, "El Empleado No Existe", "error");
                }
                
            }else{
                MisMetodos.labelMensajeValidacion(labelErrornumrut_emp,"No es un numero Valido", "error");
            }
            
            if(rutPropietarioEsNum){
                propietarioExiste = MisMetodos.existeBusqueda(propietarioDao.buscarPropietario(Integer.parseInt(inputnumrut_prop.getText())));                
                if(!propietarioExiste){
                    MisMetodos.labelMensajeValidacion(labelErrornumrut_prop, "Primero debe ingresar Nuevo Propietario", "error");
                }
               
            }else{
                MisMetodos.labelMensajeValidacion(labelErrornumrut_prop,"No es un numero Valido", "error");
            }
            
            if(superficieEsFloat){
                MisMetodos.labelMensajeValidacion(labelErrorsuperficie,"Ok","Ok");
            }else{
                MisMetodos.labelMensajeValidacion(labelErrorsuperficie,"No es numero valido","error");

            }
            
        }else{
            if(MisMetodos.InputExisteVacio(listadoInputsNoVacios) || MisMetodos.inputListadoNumeroNoValido(listadoInputsNumeros)){
                MisMetodos.inputsNoPuedenEstarVacios(listadoLabelErrorsNoVacios, listadoInputsNoVacios);
                MisMetodos.InputsExisteNumeroNoValido(listadoInputsNumeros, listadoLabelErrorNumeros);
            }else{

                PropiedadDao propiedadDao = new PropiedadDao();
                int nro_propiedad = 0;
                ArrayList<Comuna> resultadoComuna = comunaDao.buscarComuna(String.valueOf(comboBoxid_comuna.getSelectedItem()));

                if(propiedadDao.buscarPropiedad(nro_propiedad).isEmpty()){

                    String descTipoPropiedad = String.valueOf(comboBoxid_tipo_propiedad.getSelectedItem());

                    String direccion_propiedad = inputdireccion_propiedad.getText();
                    float superficie = Float.parseFloat(inputsuperficie.getText());
                    int nro_dormitorios = Integer.parseInt(inputnro_dormitorios.getText());
                    int nro_banos = Integer.parseInt(inputnro_banos.getText());
                    int valor_arriendo = Integer.parseInt(inputvalor_arriendo.getText());
                    int valor_gasto_comun = Integer.parseInt(inputvalor_gasto_comun.getText());

                    //Este valor es un tipo char por lo que no puedo ocupar misMetodos.comboBoxBuscarSeleccion(resultadoTipoPropiedad);
                    char id_tipo_propiedad = buscarSeleccionComboBoxTipoPropiedad(descTipoPropiedad);

                    int id_comuna = MisMetodos.comboBoxBuscarSeleccion(resultadoComuna);

                    int numrut_prop = Integer.parseInt(inputnumrut_prop.getText());
                    int numrut_emp = Integer.parseInt(inputnumrut_emp.getText());

                    Propiedad propiedad = new Propiedad(nro_propiedad, direccion_propiedad, superficie, nro_dormitorios, nro_banos, valor_arriendo, valor_gasto_comun, id_tipo_propiedad, id_comuna, numrut_prop, numrut_emp);

                    propiedadDao.ingresarPropiedad(propiedad);

                    JOptionPane.showMessageDialog(this, "Propiedad Ingresada");

                }else{
                    JOptionPane.showMessageDialog(this, "Propiedad Ya Existe");

                }

            }
        }
    }//GEN-LAST:event_btnIngresoNuevaPropiedadActionPerformed

    
    public char buscarSeleccionComboBoxTipoPropiedad(String tipo_propiedad){
        char idPropiedad='0';
        ArrayList<TipoPropiedad> listadoTipoPropiedad = tipoPropiedadDao.buscarTipoPropiedadPorDescripcion(tipo_propiedad);
        
        for(TipoPropiedad tipoPropiedad : listadoTipoPropiedad){
            idPropiedad = tipoPropiedad.getId_tipo_propiedad();
        }
        
        return idPropiedad;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoNuevaPropiedad;
    private javax.swing.JButton btnLimpiarIngresoNuevaPropiedad;
    private javax.swing.JComboBox<String> comboBoxid_comuna;
    private javax.swing.JComboBox<String> comboBoxid_tipo_propiedad;
    private javax.swing.JTextField inputdireccion_propiedad;
    private javax.swing.JTextField inputnro_banos;
    private javax.swing.JTextField inputnro_dormitorios;
    private javax.swing.JTextField inputnumrut_emp;
    private javax.swing.JTextField inputnumrut_prop;
    private javax.swing.JTextField inputsuperficie;
    private javax.swing.JTextField inputvalor_arriendo;
    private javax.swing.JTextField inputvalor_gasto_comun;
    private javax.swing.JLabel labelDireccion_propiedad;
    private javax.swing.JLabel labelErrordireccion_propiedad;
    private javax.swing.JLabel labelErrorid_comuna;
    private javax.swing.JLabel labelErrorid_tipo_propiedad;
    private javax.swing.JLabel labelErrornro_banos;
    private javax.swing.JLabel labelErrornro_dormitorios;
    private javax.swing.JLabel labelErrornumrut_emp;
    private javax.swing.JLabel labelErrornumrut_prop;
    private javax.swing.JLabel labelErrorsuperficie;
    private javax.swing.JLabel labelErrorvalor_arriendo;
    private javax.swing.JLabel labelErrorvalor_gasto_comun;
    private javax.swing.JLabel labelId_comuna;
    private javax.swing.JLabel labelNro_banos;
    private javax.swing.JLabel labelNumrut_emp;
    private javax.swing.JLabel labelNumrut_prop;
    private javax.swing.JLabel labelSuperficie;
    private javax.swing.JLabel labelTituloPanelIngresarPropiedad;
    private javax.swing.JLabel labelValor_arriendo;
    private javax.swing.JLabel labelValor_gasto_comun;
    private javax.swing.JLabel labelid_tipo_propiedad;
    private javax.swing.JLabel labelnro_dormitorios;
    // End of variables declaration//GEN-END:variables
}
