/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ComunaDao;
import controlador.MisMetodos;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Comuna;

/**
 *
 * @author aleja
 */
public class PanelIngresarComuna extends javax.swing.JPanel {
    ArrayList<Component> listadoInputsNoVacios = new ArrayList<>();
    ArrayList<Component> listadoLabelErrorNoVacios = new ArrayList<>();
    
    /**
     * Creates new form PanelIngresarComuna
     */
    public PanelIngresarComuna() {
        initComponents();
        MisMetodos.panelCamposErrorInicializador(this);
        listadoInputsNoVacios.add(Inputnombre_comuna);
        listadoLabelErrorNoVacios.add(labelErrornombre_comuna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreComuna = new javax.swing.JLabel();
        Inputnombre_comuna = new javax.swing.JTextField();
        btnAgregarComuna = new javax.swing.JButton();
        btnLimpiarIngresoComuna = new javax.swing.JButton();
        labelErrornombre_comuna = new javax.swing.JLabel();
        labelTituloPanelIngresarComuna = new javax.swing.JLabel();

        labelNombreComuna.setText("Nombre Comuna:");

        Inputnombre_comuna.setForeground(new java.awt.Color(153, 153, 153));
        Inputnombre_comuna.setText("Ingrese Nombre Comuna");
        Inputnombre_comuna.setName("Inputnombre_comuna"); // NOI18N
        Inputnombre_comuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inputnombre_comunaActionPerformed(evt);
            }
        });

        btnAgregarComuna.setText("Agregar Comuna");
        btnAgregarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComunaActionPerformed(evt);
            }
        });

        btnLimpiarIngresoComuna.setText("Limpiar");
        btnLimpiarIngresoComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoComunaActionPerformed(evt);
            }
        });

        labelErrornombre_comuna.setForeground(new java.awt.Color(255, 0, 0));
        labelErrornombre_comuna.setText("Algun Texto");
        labelErrornombre_comuna.setName("labelErrornombre_comuna"); // NOI18N

        labelTituloPanelIngresarComuna.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTituloPanelIngresarComuna.setText("Ingreso Nueva Comuna");
        labelTituloPanelIngresarComuna.setName("labelTituloPanelIngresarComuna"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnAgregarComuna)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarIngresoComuna))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(labelTituloPanelIngresarComuna))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelNombreComuna)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inputnombre_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelErrornombre_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelTituloPanelIngresarComuna)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreComuna)
                    .addComponent(Inputnombre_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrornombre_comuna)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarComuna)
                    .addComponent(btnLimpiarIngresoComuna))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComunaActionPerformed
        String nombre_comuna = Inputnombre_comuna.getText();
        if(MisMetodos.InputExisteVacio(listadoInputsNoVacios)){
            MisMetodos.labelMensajeValidacion(labelErrornombre_comuna, "Campo Obligatorio", "error");
        }   
        else{
            if(!MisMetodos.inputNumeroEntero(Inputnombre_comuna)){
                ComunaDao comunaDao = new ComunaDao();
                Comuna comuna = new Comuna(0, nombre_comuna);

                ArrayList<Comuna> listadoBuscarComuna = comunaDao.buscarComuna(nombre_comuna);

                if(listadoBuscarComuna.isEmpty()){
                    comunaDao.ingresarComuna(comuna);
                    JOptionPane.showMessageDialog(this,"Comuna Ingresada Correctamente");
                }else{
                    JOptionPane.showMessageDialog(this,"Comuna ya existe");
                }
            }else{
                MisMetodos.labelMensajeValidacion(labelErrornombre_comuna, "Campo No puede ser un numero","error");
            }
        }

    }//GEN-LAST:event_btnAgregarComunaActionPerformed

    private void btnLimpiarIngresoComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoComunaActionPerformed
       MisMetodos.panelLimpiarComponentes(this);
       MisMetodos.panelCamposErrorInicializador(this);
    }//GEN-LAST:event_btnLimpiarIngresoComunaActionPerformed

    private void Inputnombre_comunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inputnombre_comunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inputnombre_comunaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Inputnombre_comuna;
    private javax.swing.JButton btnAgregarComuna;
    private javax.swing.JButton btnLimpiarIngresoComuna;
    private javax.swing.JLabel labelErrornombre_comuna;
    private javax.swing.JLabel labelNombreComuna;
    private javax.swing.JLabel labelTituloPanelIngresarComuna;
    // End of variables declaration//GEN-END:variables
}