/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ComunaDao;
import controlador.PropiedadDao;
import controlador.TipoPropiedadDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Comuna;
import modelo.Propiedad;
import modelo.TipoPropiedad;

/**
 *
 * @author aleja
 */
public class PanelIngresarPropiedad extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarPropiedad
     */
    public PanelIngresarPropiedad() {
        initComponents();
        llenarComboBoxComuna();
        llenarComboBoxTipoPropiedad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiarIngresoNuevaPropiedad = new javax.swing.JButton();
        labelNumrut_emp = new javax.swing.JLabel();
        btnVolverIngresoNuevaPropiedad = new javax.swing.JButton();
        inputDireccion_propiedad = new javax.swing.JTextField();
        comboBoxTipoPropiedad = new javax.swing.JComboBox<>();
        labelDireccion_propiedad = new javax.swing.JLabel();
        inputSuperficie = new javax.swing.JTextField();
        comboBoxComuna = new javax.swing.JComboBox<>();
        labelSuperficie = new javax.swing.JLabel();
        inputNroDormitorios = new javax.swing.JTextField();
        labelnro_dormitorios = new javax.swing.JLabel();
        inputNro_banos = new javax.swing.JTextField();
        labelNro_banos = new javax.swing.JLabel();
        inputValor_arriendo = new javax.swing.JTextField();
        labelValor_arriendo = new javax.swing.JLabel();
        inputValor_gasto_comun = new javax.swing.JTextField();
        labelValor_gasto_comun = new javax.swing.JLabel();
        inputNumrut_prop = new javax.swing.JTextField();
        labelid_tipo_propiedad = new javax.swing.JLabel();
        inputNumrut_emp = new javax.swing.JTextField();
        labelId_comuna = new javax.swing.JLabel();
        btnIngresoNuevaPropiedad = new javax.swing.JButton();
        labelNumrut_prop = new javax.swing.JLabel();

        btnLimpiarIngresoNuevaPropiedad.setText("Limpiar");
        btnLimpiarIngresoNuevaPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoNuevaPropiedadActionPerformed(evt);
            }
        });

        labelNumrut_emp.setText("Numero Rut Empleado");

        btnVolverIngresoNuevaPropiedad.setText("Volver");
        btnVolverIngresoNuevaPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverIngresoNuevaPropiedadActionPerformed(evt);
            }
        });

        inputDireccion_propiedad.setForeground(new java.awt.Color(153, 153, 153));
        inputDireccion_propiedad.setText("Ingrese Direccion Propiedad");

        labelDireccion_propiedad.setText("Direccion Propiedad");

        inputSuperficie.setForeground(new java.awt.Color(153, 153, 153));
        inputSuperficie.setText("Ingrese Superficie Propiedad");

        labelSuperficie.setText("Superficie");

        inputNroDormitorios.setForeground(new java.awt.Color(153, 153, 153));
        inputNroDormitorios.setText("Ingrese numero de Dormitorios");

        labelnro_dormitorios.setText("Nro Dormitorios");

        inputNro_banos.setForeground(new java.awt.Color(153, 153, 153));
        inputNro_banos.setText("Ingrese Cantidad de Baños");

        labelNro_banos.setText("Nro baños");

        inputValor_arriendo.setForeground(new java.awt.Color(153, 153, 153));
        inputValor_arriendo.setText("Ingrese valor Arriendo");

        labelValor_arriendo.setText("Valor Arriendo");

        inputValor_gasto_comun.setForeground(new java.awt.Color(153, 153, 153));
        inputValor_gasto_comun.setText("Ingrese Valor Gastos Comunes");

        labelValor_gasto_comun.setText("Valor Gasto Comun");

        inputNumrut_prop.setForeground(new java.awt.Color(153, 153, 153));
        inputNumrut_prop.setText("Ingrese numero de rut propietario");

        labelid_tipo_propiedad.setText("Id tipo propiedad");

        inputNumrut_emp.setForeground(new java.awt.Color(153, 153, 153));
        inputNumrut_emp.setText("Ingrese Rut Empleado");

        labelId_comuna.setText("Id Comuna");

        btnIngresoNuevaPropiedad.setText("Ingreso Nueva Propiedad");
        btnIngresoNuevaPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoNuevaPropiedadActionPerformed(evt);
            }
        });

        labelNumrut_prop.setText("Numero Rut Propietario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresoNuevaPropiedad)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverIngresoNuevaPropiedad)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarIngresoNuevaPropiedad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelnro_dormitorios)
                            .addComponent(labelValor_arriendo)
                            .addComponent(labelValor_gasto_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelid_tipo_propiedad)
                            .addComponent(labelNumrut_emp)
                            .addComponent(labelNumrut_prop)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDireccion_propiedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelSuperficie))
                            .addComponent(labelNro_banos)
                            .addComponent(labelId_comuna))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputNumrut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxTipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNroDormitorios)
                            .addComponent(inputNro_banos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDireccion_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputValor_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputValor_gasto_comun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNumrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDireccion_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDireccion_propiedad))
                        .addGap(18, 18, 18)
                        .addComponent(inputSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelSuperficie, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNroDormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnro_dormitorios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNro_banos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNro_banos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputValor_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor_arriendo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputValor_gasto_comun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor_gasto_comun))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelid_tipo_propiedad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId_comuna))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumrut_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumrut_prop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumrut_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumrut_emp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresoNuevaPropiedad)
                    .addComponent(btnVolverIngresoNuevaPropiedad)
                    .addComponent(btnLimpiarIngresoNuevaPropiedad))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarIngresoNuevaPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoNuevaPropiedadActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarIngresoNuevaPropiedadActionPerformed

    private void btnVolverIngresoNuevaPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverIngresoNuevaPropiedadActionPerformed
        //dispose();
    }//GEN-LAST:event_btnVolverIngresoNuevaPropiedadActionPerformed

    private void btnIngresoNuevaPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoNuevaPropiedadActionPerformed
        PropiedadDao propiedadDao = new PropiedadDao();
        int nro_propiedad = 0;

        if(propiedadDao.buscarPropiedad(nro_propiedad).isEmpty()){

            String descComuna = String.valueOf(comboBoxComuna.getSelectedItem());
            String descTipoPropiedad = String.valueOf(comboBoxTipoPropiedad.getSelectedItem());

            String direccion_propiedad = inputDireccion_propiedad.getText();
            float superficie = Float.valueOf(inputSuperficie.getText());
            int nro_dormitorios = Integer.parseInt(inputNroDormitorios.getText());
            int nro_banos = Integer.parseInt(inputNro_banos.getText());
            int valor_arriendo = Integer.parseInt(inputValor_arriendo.getText());
            int valor_gasto_comun = Integer.parseInt(inputValor_gasto_comun.getText());
            char id_tipo_propiedad = buscarSeleccionComboBoxTipoPropiedad(descTipoPropiedad);
            int id_comuna = buscarSeleccionComboBoxComuna(descComuna);
            int numrut_prop = Integer.parseInt(inputNumrut_prop.getText());
            int numrut_emp = Integer.parseInt(inputNumrut_emp.getText());

            Propiedad propiedad = new Propiedad(nro_propiedad, direccion_propiedad, superficie, nro_dormitorios, nro_banos, valor_arriendo, valor_gasto_comun, id_tipo_propiedad, id_comuna, numrut_prop, numrut_emp);

            propiedadDao.ingresarPropiedad(propiedad);

            JOptionPane.showMessageDialog(this, "Propiedad Ingresada");

        }else{
            JOptionPane.showMessageDialog(this, "Propiedad Ya Existe");

        }
    }//GEN-LAST:event_btnIngresoNuevaPropiedadActionPerformed
 public void llenarComboBoxTipoPropiedad(){
        TipoPropiedadDao tipoPropiedadDao = new TipoPropiedadDao();
        ArrayList<TipoPropiedad> listadoTipoPropiedadDao = tipoPropiedadDao.todosLosTipoPropiedad();
        
        for(TipoPropiedad tipopropiedad : listadoTipoPropiedadDao){
            
            String desc_tipoPropiedad = tipopropiedad.getDesc_tipo_propiedad();
            comboBoxTipoPropiedad.addItem(desc_tipoPropiedad);
        }
    }
    
    public void llenarComboBoxComuna(){
        ComunaDao comunaDao = new ComunaDao();
        ArrayList<Comuna> listadoComuna = comunaDao.mostrarComunas();
        
        for(Comuna comuna : listadoComuna){
            String desc_comuna = comuna.getNombre_comuna();
            comboBoxComuna.addItem(desc_comuna);
        }
    }
    
    public char buscarSeleccionComboBoxTipoPropiedad(String tipo_propiedad){
        char idPropiedad='0';
        TipoPropiedadDao tipoPropiedadDao = new TipoPropiedadDao();
        ArrayList<TipoPropiedad> listadoTipoPropiedad = tipoPropiedadDao.buscarTipoPropiedadPorDescripcion(tipo_propiedad);
        
        for(TipoPropiedad tipoPropiedad : listadoTipoPropiedad){
            idPropiedad = tipoPropiedad.getId_tipo_propiedad();
        }
        
        return idPropiedad;
    }
    
    public int buscarSeleccionComboBoxComuna(String desc_Comuna){
        int id_comuna = 0;
        
        ComunaDao comunaDao = new ComunaDao();
        ArrayList<Comuna> listadoComuna = comunaDao.buscarComuna(desc_Comuna);
        
        for(Comuna comuna : listadoComuna){
            id_comuna = comuna.getId_comuna();
            
        }
        return id_comuna;
    }
    
    private void limpiar(){
        JTextField caja;
        PanelIngresarPropiedad panelIngresarPropiedad = new PanelIngresarPropiedad();
        comboBoxComuna.setSelectedIndex(0);
        comboBoxTipoPropiedad.setSelectedIndex(0);
        for (int i = 0; i < panelIngresarPropiedad.getComponentCount(); i++) {
            if(panelIngresarPropiedad.getComponent(i).getName().equals("javax.swing.JTextField"));
                caja = (JTextField)panelIngresarPropiedad.getComponent(i);
                caja.setText("");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoNuevaPropiedad;
    private javax.swing.JButton btnLimpiarIngresoNuevaPropiedad;
    private javax.swing.JButton btnVolverIngresoNuevaPropiedad;
    private javax.swing.JComboBox<String> comboBoxComuna;
    private javax.swing.JComboBox<String> comboBoxTipoPropiedad;
    private javax.swing.JTextField inputDireccion_propiedad;
    private javax.swing.JTextField inputNroDormitorios;
    private javax.swing.JTextField inputNro_banos;
    private javax.swing.JTextField inputNumrut_emp;
    private javax.swing.JTextField inputNumrut_prop;
    private javax.swing.JTextField inputSuperficie;
    private javax.swing.JTextField inputValor_arriendo;
    private javax.swing.JTextField inputValor_gasto_comun;
    private javax.swing.JLabel labelDireccion_propiedad;
    private javax.swing.JLabel labelId_comuna;
    private javax.swing.JLabel labelNro_banos;
    private javax.swing.JLabel labelNumrut_emp;
    private javax.swing.JLabel labelNumrut_prop;
    private javax.swing.JLabel labelSuperficie;
    private javax.swing.JLabel labelValor_arriendo;
    private javax.swing.JLabel labelValor_gasto_comun;
    private javax.swing.JLabel labelid_tipo_propiedad;
    private javax.swing.JLabel labelnro_dormitorios;
    // End of variables declaration//GEN-END:variables
}
