/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import controlador.MisMetodos;
import modelo.TipoPropiedad;
import controlador.TipoPropiedadDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author aleja
 */
public class PanelIngresarTipoPropiedad extends javax.swing.JPanel {
    
    TipoPropiedad tipoPropiedad;
    /**
     * Creates new form PanelIngresarTipoPropiedad
     */
    public PanelIngresarTipoPropiedad() {
        initComponents();
        MisMetodos.panelCamposErrorInicializador(this);
        MisMetodos.panelCamposErrorInicializador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputdesc_tipo_propiedad = new javax.swing.JTextField();
        btnIngresoTipoPropiedad = new javax.swing.JButton();
        btnLimpiarIngresoTipoPropiedad = new javax.swing.JButton();
        labelId_tipo_propiedad = new javax.swing.JLabel();
        labelDesc_tipo_propiedad = new javax.swing.JLabel();
        inputid_tipo_propiedad = new javax.swing.JTextField();
        labelErrorid_tipo_propiedad = new javax.swing.JLabel();
        labelErrordesc_tipo_propiedad = new javax.swing.JLabel();
        labelTituloPanelIngresoTipoPropiedad = new javax.swing.JLabel();

        inputdesc_tipo_propiedad.setForeground(new java.awt.Color(153, 153, 153));
        inputdesc_tipo_propiedad.setText("Ingrese Descripcion Tipo Propiedad");
        inputdesc_tipo_propiedad.setName("inputdesc_tipo_propiedad"); // NOI18N

        btnIngresoTipoPropiedad.setText("Ingreso Tipo Propiedad");
        btnIngresoTipoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoTipoPropiedadActionPerformed(evt);
            }
        });

        btnLimpiarIngresoTipoPropiedad.setText("Limpiar");
        btnLimpiarIngresoTipoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoTipoPropiedadActionPerformed(evt);
            }
        });

        labelId_tipo_propiedad.setText("Id Tipo Propiedad");

        labelDesc_tipo_propiedad.setText("Descripción Tipo Propiedad");

        inputid_tipo_propiedad.setForeground(new java.awt.Color(153, 153, 153));
        inputid_tipo_propiedad.setText("Ingrese Id Tipo Propiedad");
        inputid_tipo_propiedad.setName("inputid_tipo_propiedad"); // NOI18N

        labelErrorid_tipo_propiedad.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorid_tipo_propiedad.setText("Id Tipo Propiedad Obligatorio");
        labelErrorid_tipo_propiedad.setName("labelErrorid_tipo_propiedad"); // NOI18N

        labelErrordesc_tipo_propiedad.setForeground(new java.awt.Color(255, 0, 0));
        labelErrordesc_tipo_propiedad.setText("Descripción Tipo Propiedad Obligatorio");
        labelErrordesc_tipo_propiedad.setName("labelErrordesc_tipo_propiedad"); // NOI18N

        labelTituloPanelIngresoTipoPropiedad.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTituloPanelIngresoTipoPropiedad.setText("Ingreso Nuevo Tipo Propiedad");
        labelTituloPanelIngresoTipoPropiedad.setName("labelTituloPanelIngresoTipoPropiedad"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelId_tipo_propiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDesc_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelErrordesc_tipo_propiedad)
                                .addComponent(labelErrorid_tipo_propiedad)
                                .addComponent(inputdesc_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputid_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTituloPanelIngresoTipoPropiedad)
                            .addGap(90, 90, 90)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresoTipoPropiedad)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarIngresoTipoPropiedad)))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloPanelIngresoTipoPropiedad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId_tipo_propiedad)
                    .addComponent(inputid_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorid_tipo_propiedad)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesc_tipo_propiedad)
                    .addComponent(inputdesc_tipo_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrordesc_tipo_propiedad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresoTipoPropiedad)
                    .addComponent(btnLimpiarIngresoTipoPropiedad))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoTipoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoTipoPropiedadActionPerformed
        boolean idEsChar = MisMetodos.inputEsChar(inputid_tipo_propiedad);
        boolean idEsVacio = inputid_tipo_propiedad.getText().isEmpty();
        
        boolean descEsVacio = inputdesc_tipo_propiedad.getText().isEmpty();
        
        if(!idEsChar || idEsVacio || descEsVacio){
            
            if(!idEsChar){
                MisMetodos.labelMensajeValidacion(labelErrorid_tipo_propiedad, "Debe Ingresar un solo valor","error");
            }
            if(idEsVacio){
                MisMetodos.labelMensajeValidacion(labelErrorid_tipo_propiedad, "Campo Obligatorio","error");
            }
            if(descEsVacio){
                MisMetodos.labelMensajeValidacion(labelErrordesc_tipo_propiedad, "Campo Obligatorio","error");
            }
            
            
        }else{
        
            TipoPropiedadDao tipoPropiedadDao = new TipoPropiedadDao();

            char id_tipoPropiedad  = inputid_tipo_propiedad.getText().charAt(0);
            String desc_tipoPropiedad = inputdesc_tipo_propiedad.getText();

            ArrayList <TipoPropiedad> listadoTipoPropiedadID = tipoPropiedadDao.buscarTipoPropiedadPorId(id_tipoPropiedad);
            ArrayList <TipoPropiedad> listadoTipoPropiedadDescripcion = tipoPropiedadDao.buscarTipoPropiedadPorDescripcion(desc_tipoPropiedad);

            if(listadoTipoPropiedadID.isEmpty()){

                tipoPropiedad = new TipoPropiedad(id_tipoPropiedad, desc_tipoPropiedad);

                tipoPropiedadDao.ingresarTipoPropiedad(tipoPropiedad);

                JOptionPane.showMessageDialog(this,"Tipo Propiedad Ingresada");
            }
            else{
                JOptionPane.showMessageDialog(this,"Tipo propiedad Ya existe o La Descripcion Ya existe");
            }
        }
    }//GEN-LAST:event_btnIngresoTipoPropiedadActionPerformed

    private void btnLimpiarIngresoTipoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoTipoPropiedadActionPerformed
        MisMetodos.panelLimpiarComponentes(this);
        MisMetodos.panelCamposErrorInicializador(this);

    }//GEN-LAST:event_btnLimpiarIngresoTipoPropiedadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoTipoPropiedad;
    private javax.swing.JButton btnLimpiarIngresoTipoPropiedad;
    private javax.swing.JTextField inputdesc_tipo_propiedad;
    private javax.swing.JTextField inputid_tipo_propiedad;
    private javax.swing.JLabel labelDesc_tipo_propiedad;
    private javax.swing.JLabel labelErrordesc_tipo_propiedad;
    private javax.swing.JLabel labelErrorid_tipo_propiedad;
    private javax.swing.JLabel labelId_tipo_propiedad;
    private javax.swing.JLabel labelTituloPanelIngresoTipoPropiedad;
    // End of variables declaration//GEN-END:variables
}
