/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.EstadoCivil;
import controlador.EstadoCivilDao;

import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author aleja
 */
public class VentanaIngresarEstadoCivil extends javax.swing.JFrame {

    /**
     * Creates new form ventanaIngresarEstadoCivil
     */
    public VentanaIngresarEstadoCivil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngresasrEstadoCivil = new javax.swing.JPanel();
        labelDescripcionEstadoCivil = new javax.swing.JLabel();
        InputDesc_estcivil = new javax.swing.JTextField();
        btnGuardarEstadoCivil = new javax.swing.JButton();
        btnLimpiarEstadoCivil = new javax.swing.JButton();
        btnVolverEstadoCivil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelIngresasrEstadoCivil.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Estado Civil"));

        labelDescripcionEstadoCivil.setText("Nombre Estado Civil: ");

        InputDesc_estcivil.setForeground(new java.awt.Color(153, 153, 153));
        InputDesc_estcivil.setText("Ingrese Estado Civil");

        btnGuardarEstadoCivil.setText("Guardar Estado Civil");
        btnGuardarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstadoCivilActionPerformed(evt);
            }
        });

        btnLimpiarEstadoCivil.setText("Limpiar");
        btnLimpiarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEstadoCivilActionPerformed(evt);
            }
        });

        btnVolverEstadoCivil.setText("Volver");
        btnVolverEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverEstadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresasrEstadoCivilLayout = new javax.swing.GroupLayout(panelIngresasrEstadoCivil);
        panelIngresasrEstadoCivil.setLayout(panelIngresasrEstadoCivilLayout);
        panelIngresasrEstadoCivilLayout.setHorizontalGroup(
            panelIngresasrEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresasrEstadoCivilLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelIngresasrEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescripcionEstadoCivil)
                    .addComponent(btnGuardarEstadoCivil))
                .addGap(18, 18, 18)
                .addGroup(panelIngresasrEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresasrEstadoCivilLayout.createSequentialGroup()
                        .addComponent(btnLimpiarEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InputDesc_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelIngresasrEstadoCivilLayout.setVerticalGroup(
            panelIngresasrEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresasrEstadoCivilLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panelIngresasrEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescripcionEstadoCivil)
                    .addComponent(InputDesc_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(panelIngresasrEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEstadoCivil)
                    .addComponent(btnLimpiarEstadoCivil)
                    .addComponent(btnVolverEstadoCivil))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIngresasrEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIngresasrEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstadoCivilActionPerformed
        
        String desc_EstCivil;
       
        desc_EstCivil = InputDesc_estcivil.getText();
        
        EstadoCivil estadoCivil = new EstadoCivil(0, desc_EstCivil);
        
        EstadoCivilDao estadoCivilDao = new EstadoCivilDao();
        
        if(estadoCivilDao.buscarEstadoCivil(desc_EstCivil).isEmpty()){
            estadoCivilDao.agregarEstadoCivil(estadoCivil);
        
            JOptionPane.showMessageDialog(this, "Estado Civil Ingresado");
        
        }else{
            JOptionPane.showMessageDialog(this,"Estado Civil Ya Existe");
        }
    }//GEN-LAST:event_btnGuardarEstadoCivilActionPerformed

    private void btnLimpiarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEstadoCivilActionPerformed
        JTextField caja;
        
        for (int i = 0; i < panelIngresasrEstadoCivil.getComponentCount(); i++) {
            if(panelIngresasrEstadoCivil.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)panelIngresasrEstadoCivil.getComponent(i);
                caja.setText("");
            }
        }
    }//GEN-LAST:event_btnLimpiarEstadoCivilActionPerformed

    private void btnVolverEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverEstadoCivilActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverEstadoCivilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarEstadoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIngresarEstadoCivil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputDesc_estcivil;
    private javax.swing.JButton btnGuardarEstadoCivil;
    private javax.swing.JButton btnLimpiarEstadoCivil;
    private javax.swing.JButton btnVolverEstadoCivil;
    private javax.swing.JLabel labelDescripcionEstadoCivil;
    private javax.swing.JPanel panelIngresasrEstadoCivil;
    // End of variables declaration//GEN-END:variables
}
